### ISSUE TITLE
`resources` should be `data` in minimal example in top-level README.md 

### ISSUE THREAD

**Issue by kersson** [bazelbuild/rules_apple#1005]
The `objc_library` rule in the [minimal example](https://github.com/bazelbuild/rules_apple/blob/bfebdd1cd97e192acfbb647f697f3c78eeb28e33/README.md#examples) of the top-level README.md has an error. The `resources` attribute should be `data`:
```bazel
objc_library(
    name = "Lib",
    srcs = glob([
        "**/*.h",
        "**/*.m",
    ]),
    resources = [  #<-- should be `data`
        ":Main.storyboard",
    ],
)
```

**Comment by keith** [comment]
Very true! Mind submitting that change?

**Comment by kersson** [comment]
Sure! Need to get the CLA in place, then I'll submit a PR.

**Comment by kersson** [comment]
CLA is finally in place and the PR is ready!
