### ISSUE TITLE
SwiftInfo.module name has been deprecated

### ISSUE THREAD

**Issue by jiayi-zhou** [bazelbuild/rules_apple#1012]
In `rules_apple/apple/internal/aspects/resource_aspect.bzl`, the line `bucketize_args["swift_module"] = target[SwiftInfo].module_name` causes an error: `Error: 'SwiftInfo' value has no field or method 'module_name'` as module_name has been deprecated (see: https://github.com/bazelbuild/rules_swift/commit/c512f8e59b4c9084cede72276bbf30f6df4342f7).

**Comment by thii** [comment]
It's fixed in 7749a9afb005f80b67eec79c692930e99fbd2f2e. You have to use rules_apple at HEAD if you're using rules_swift at HEAD.

**Comment by jiayi-zhou** [comment]
My bad, thanks!
