### ISSUE TITLE
Depending on a cc_library from a swift_library not working

### ISSUE THREAD

**Issue by perezd** [bazelbuild/rules_apple#103]
Trying to compile this:
https://github.com/grpc/grpc-swift/tree/master/Sources

the subproject gRPC depends on CgRPC which I have compiling as a cc_library.
What is the right way to accomplish this?

**Comment by dmishe** [comment]
Hm, you would need a `objc_library` that exposes just the Objective-C/C part of CgRPC in its public headers.

**Comment by perezd** [comment]
Yes I realized that too late, sorry. This is WAI.
