### ISSUE TITLE
Adding Firebase to Bazel project

### ISSUE THREAD

**Issue by vchernyshov** [bazelbuild/rules_apple#1091]
Hello, I have a Bazel iOS project and I need to add Firebase dependency.
Firebase provided as a zip with set of Xcode frameworks.
I'm trying to add it like this:
`
apple_static_framework_import(
  name = "BoringSSLGRPC",
  framework_imports = glob(["BoringSSL-GRPC.xcframework/ios-arm64_i386_x86_64-simulator/BoringSSL-GRPC.framework/**"]),
  visibility = [
    "//visibility:public",
  ],
)

apple_static_framework_import(
  name = "FirebaseAnalytics",
  framework_imports = glob(["FirebaseAnalytics.xcframework/ios-arm64_i386_x86_64-simulator/FirebaseAnalytics.framework/**"]),
  visibility = ["//visibility:public"],
)`

Bazel generates Xcode project but error occurred when I build the project:
`/var/tmp/_bazel_vchernyshov/8432bf40a9c3dc219067a8a2fb9ccda3/execroot/__main__/submodules/Pods/BoringSSL-GRPC.xcframework/ios-arm64_i386_x86_64-simulator/BoringSSL-GRPC.framework/Modules/module.modulemap:1:27: Skipping stray token`
`/var/tmp/_bazel_vchernyshov/8432bf40a9c3dc219067a8a2fb9ccda3/execroot/__main__/submodules/Pods/BoringSSL-GRPC.xcframework/ios-arm64_i386_x86_64-simulator/BoringSSL-GRPC.framework/Modules/module.modulemap:1:28: Expected '{' to start module 'BoringSSL'`

Could say what I'm doing wrong?

**Comment by brentleyjones** [comment]
xcframeworks are currently not supported:

- https://github.com/bazelbuild/rules_apple/issues/355
- https://github.com/bazelbuild/rules_apple/issues/851

**Comment by tinder-maxwellelliott** [comment]
> if I put content from `ios-arm64_i386_x86_64-simulator/BoringSSL-GRPC.framework/` to folder `BoringSSL-GRPC` without `xcframework` could this helps me?

It can help, but you would need to use something like `[select](https://docs.bazel.build/versions/master/configurable-attributes.html)` to choose the right version of the `.framework` file for the built architecture

**Comment by thii** [comment]
This is possible now with the new `apple_static_xcframework_import` rule.

```
apple_static_framework_import(
  name = "FirebaseAnalytics",
  xcframework_imports = glob(["FirebaseAnalytics.xcframework/**"]),
  visibility = ["//visibility:public"],
)
```
