### ISSUE TITLE
Upload to App Store Connect

### ISSUE THREAD

**Issue by shreyasthiagaraj** [bazelbuild/rules_apple#1129]
Is it possible to automate this using Bazel? I want to enable the equivalent of this:
https://docs.fastlane.tools/getting-started/ios/appstore-deployment/

**Comment by keith** [comment]
Bazel does not provide any integrations for uploading your builds. You can continue to use fastlane or [altool](https://stackoverflow.com/a/56436346) to upload bazel built apps
