### ISSUE TITLE
app_icons doesn't update the Info.plist, leading to an error when uploading app with Application Loader

### ISSUE THREAD

**Issue by jbeder** [bazelbuild/rules_apple#123]
Given:

```
ios_application(
    name = "myapp",
    app_icons = glob([". appiconset/Icon*.png"]),
    ....
)
````

with that directory consisting of:

```
$ ls Icon*.png
Icon-60.png		Icon-76@2x.png		Icon-Small.png
Icon-60@2x.png		Icon-Small-40.png	Icon-Small@2x.png
Icon-60@3x.png		Icon-Small-40@2x.png	Icon-Small@3x.png
Icon-72.png		Icon-Small-40@3x.png	Icon.png
Icon-72@2x.png		Icon-Small-50.png	Icon@2x.png
Icon-76.png		Icon-Small-50@2x.png
```

I get the errors when uploading:

```
[...] ERROR: ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0."
[...] ERROR: ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '76x76' pixels, in .png format for iOS versions >= 7.0."
[...] ERROR: ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 7.0."
```

If I add the key/value pair to the `Info.plist` file:

```
<key>CFBundleIconFiles</key>
    <array>
      <string>Icon-60.png</string>
      <string>Icon-60@2x.png</string>
      <string>Icon-60@3x.png</string>
      <string>Icon-72.png</string>
      <string>Icon-72@2x.png</string>
      <string>Icon-76.png</string>
      <string>Icon-76@2x.png</string>
      <string>Icon-Small-40.png</string>
      <string>Icon-Small-40@2x.png</string>
      <string>Icon-Small-40@3x.png</string>
      <string>Icon-Small-50.png</string>
      <string>Icon-Small-50@2x.png</string>
      <string>Icon-Small.png</string>
      <string>Icon-Small@2x.png</string>
      <string>Icon-Small@3x.png</string>
      <string>Icon.png</string>
      <string>Icon@2x.png</string>
    </array>
```

(that is, explicitly listing all of the icons)

then it works correctly, uploading with Application Loader without an error.

I think bazel might have to generate that key/value pair in the Info.plist file that gets attached to the app.

**Comment by allevato** [comment]
The appicons and launch_images attributes only accept asset catalogs, not
general globs of icons. If you use an asset catalog, then the plist
fragment will get generated for you.

The examples in this repo can be used as a reference for the way to glob
these.

**Comment by jbeder** [comment]
Where is that documented? In the `ios_application` [rule documentation](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md), it just says

> Each file must have a containing directory named *.xcassets/*.appiconset and there may be only one such .appiconset directory in the list.

Moreover, it looks like the only difference is the `Contents.json` file, which could be auto-generated from the icons and their names themselves. Is this right?

Also, the `Contents.json` metadata looks like it gets removed in the `Info.plist` file, which just requires a list of names. Why can't `app_icons` just take a list of icons?

**Comment by StevenEWright** [comment]
Interesting question. On the flip side, why invent another convention for file naming (which requires further documentation and maintenance) when an idiomatic, well documented, and flexible standard (asset catalogs) already exists for this purpose?

Setting aside issues related to skylark rules maintenance, I appreciate and prefer the existing asset catalog approach for a couple reasons. For one, the asset catalog creation tools let me do things like preview layered icons for tvOS. 

Though it seems like the error messaging could be improved, at least, to say “hey, this doesn’t look like an asset catalog”.

**Comment by jbeder** [comment]
I suppose that's fair, if that's what the Bazel project wants to decide.

I'd suggest to (a) improve the documentation, and (b) as you say, improve the error message.

Also, is there a standard way to construct asset catalogs? That is, a command line tool provided by Apple? I sorta dispute the notion that asset catalogs are well-documented, since it tool me forever to figure this out, and I still am not sure what format to put my icons in.

**Comment by allevato** [comment]
The use of asset catalogs was meant to be implied by the statement that the files must be located in a directory named `*.xcassets/*.appiconset`, but we can certainly improve/clarify that.

We also print an error if you have multiple `*.appiconset` directories captured by the same glob (because then we wouldn't know which one to use), but we don't say anything if the glob produces zero icons of that path format. We should fix that.

The JSON files could theoretically be generated from the icons based on their filenames, but that's kind of backwards from how Apple's tools work today—now the filenames don't matter, and the JSON info dictates which resolutions/devices the icons are supposed to be used on. We'd prefer not to deviate from Apple's workflows/formats too much, for reasons like @StevenEWright mentioned—iOS icons may be "simple", but tvOS ones are much more complex (multiple layers), and asset catalogs are already the right format for that.

I believe most people just manage their asset catalogs in Xcode, where you can create them and manipulate them with their UI. Are you trying to use a workflow that doesn't include Xcode at all?

**Comment by jbeder** [comment]
Correct, I'm not using Xcode to *produce* any files (except through Tulsi to do my normal editing).

And my designer just makes the icons and sends me those with appropriate size. If there was some tool (other than Xcode) I could tell him to use (including a command line tool) that would be fine too.

**Comment by allevato** [comment]
A command-line tool that generates the right Contents.json is an interesting idea, but would be fairly complex if intended to be complete (there are a large number of asset types that you can place in a catalog) and would need to be kept up-to-date with new Xcode/OS releases. Still, something that looks at a directory of icons and decides which entries you need based on the sizes of icons you've been given could be appealing.

Is there a reason you don't want to use Xcode to manage these catalogs? You can even create a folder named `*.xcassets` and drag it onto Xcode's dock icon and it will let you manipulate it independently without being associated with a project (but if you're working with Tulsi, then you'd have it associated with your project as well).

**Comment by StevenEWright** [comment]
<Sorry, meant to post this yesterday - some duplicate info now - but too lazy to rewrite :) >

Thinking about this further...

In regards to the documentation...

The asset catalog format reference seems pretty comprehensive to me?

https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/index.html#//apple_ref/doc/uid/TP40015170-CH18-SW1

¯\_(ツ)_/¯

As to tooling...

So Apple does not provide a command line tool for generating the necessary folder structure and JSON files that I’m aware of.

Personally, I just crack open Xcode, start a new project of the appropriate type, update the template project’s asset catalog, and then copy it out to my real project.

But I realize you’re probably trying to avoid that - and I think the best way to do so may actually be through a simple Bazel macro that generates the asset catalog and returns a filegroup - using a template asset catalog and files in the macro’s parameters for your actual PNGs.

@allevato Does that seem like a reasonable approach to you?

Even if rules_apple maintainers don’t want to include it in their repo, it does seem like a nice little macro to have lying around. If I were in your shoes, I think this is the solution I’d try first. But people here would know better than me.

Does that seem like it would be a viable solution for you?

**Comment by thomasvl** [comment]
@jbeder the initial report includes:

> `app_icons = glob([". appiconset/Icon*.png"]),`

Is that glob right?  "[period][space]appiconset"?  Seems like that shouldn't even work.

**Comment by jbeder** [comment]
@thomasvl you're right, that's a typo

@StevenEWright the documentation for the *format* is fine (although as discussed in this thread, it's not clear from the rules_apple docs that it requires the format); but the connection with app icons and sizes themselves is missing, I think. That is, going from [here](https://developer.apple.com/library/content/qa/qa1686/_index.html) to [there](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/index.html#//apple_ref/doc/uid/TP40015170-CH18-SW1) wasn't obvious to me.
