### ISSUE TITLE
xcarchive bundling

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_apple#1234]
Starting this issue to see if folks would be interested in having `.xcarchive` bundling in place of `.ipa`. It's useful for sending the + `.dSYMS` to Apple.

The format is pretty simple in itself.

See https://developer.apple.com/documentation/xcode/building-your-app-to-include-debugging-information

**Comment by keith** [comment]
I think @thii has a rule for this, I'm not sure if it's public anywhere

**Comment by steeve** [comment]
I'll gladly open source mine then

**Comment by tinder-maxwellelliott** [comment]
@steeve Did you ever get to open sourcing your approach? Looking at implementing this myself

**Comment by sanju-naik** [comment]
Any update on open sourcing this? even we are also looking to generate xcarchives using Bazel.

**Comment by rockwotj** [comment]
I am also interested in a rule for this :)

**Comment by keith** [comment]
For folks who are just interested in the case of uploading dSYMs to apple, you can use this attribute https://github.com/bazelbuild/rules_apple/blob/76752fe84ff0dc5d793033015647c78efbf41309/doc/rules-ios.md#ios_application-include_symbols_in_bundle to include `Symbols` files in the produced `.ipa` which are used for the same purpose AFAIUI. That is what we're doing at Lyft and our crash reports in Xcode have correct symbols

**Comment by jerrymarino** [comment]
+1 this is such a super common use case for iOS developers and quite easy to get wrong. I like the idea of having an executable deploy rule end to end from Bazel: e.g. rules_docker has some push rules already. What would be sweet is this:
```
itunes_connect_deployment(name="some_deployment", app=":some_app")
```

Then you can just run `bazel run :some_deployment` and have it uploaded. But, I imagine adding the xcarchive rule as it's own piece could help form various deploy rules out of it, or upload to other places..

**Comment by rockwotj** [comment]
+1 to streamlining this, I just spent at least a day getting dsyms, provisioning profiles, signing certs and etc setup with Bazel. The information is spread all over. It'd be great if there was a guide on how to get a deployable iOS app with Bazel going and the best practices... Maybe I should write up a blog post 🤔


On another note I also did the same thing getting xcode up and running with xchammer and it's still not quite there (some xcframeworks aren't recognized by xcode).. maybe https://github.com/buildbuddy-io/rules_xcodeproj is the answer?

**Comment by keith** [comment]
> +1 to streamlining this, I just spent at least a day getting dsyms, provisioning profiles, signing certs and etc setup with Bazel. The information is spread all over. It'd be great if there was a guide on how to get a deployable iOS app with Bazel going and the best practices... Maybe I should write up a blog post 🤔

We haven't spent much time on the onboarding docs in general, i think it would be great if we included all of this somewhere in the docs in this repo. The bazel team has been asking us to replace the iOS tutorial for similar reasons

**Comment by jerrymarino** [comment]
> On another note I also did the same thing getting xcode up and running with xchammer

Ah interesting, yep the projects are designed to get editing working and be as small as possible from a performance standpoint  - because of this it is not well suited to make an an archive. 

My 2 cents - I'd rather see us work towards a rule to do this than rely on Xcode for more stuff

**Comment by anthonydito** [comment]
Circling back on this. Would anybody be willing to share what their process for submitting an app to App Store Connect looks like from bazel? Struggling to produce an IPA that I can upload via Transporter at the moment by just running a `bazel build ios`

**Comment by luispadron** [comment]
Started the work for this rule over here #1980

**Comment by luispadron** [comment]
https://github.com/bazelbuild/rules_apple/pull/1980 is merged, we can probably close this now or keep it to track additions

**Comment by mattrobmattrob** [comment]
Closed. Thanks, @luispadron! Please open a new issue if there's missing functionality in the new `xcarchive` rule.
