### ISSUE TITLE
Xcode13 - Unable to Install to device after the initial build

### ISSUE THREAD

**Issue by OliverKoo** [bazelbuild/rules_apple#1237]
@keith after merging in [this fix](https://github.com/bazelbuild/rules_apple/issues/1216#issuecomment-900713650) you suggested from other thread. We were able to build to device using Xcode13.

However tho it only works on the initial build to device. All the subsequent build will encounter "Unable to Install" Error
![Screen Shot 2021-09-20 at 10 19 22 AM](https://user-images.githubusercontent.com/40183324/134064008-fede4b4e-8f25-452b-b05b-efcfdeb392d4.png)

I suspect this has to do with us switching to the New Build System in Xcode. The  ios_extension that @keith helped us solve appeared also when we were forced to switch to the New Build System.

Wondering if anybody here seen this before or have suggestions of a workaround? I made a StackOverflow post as well with more details captured.
https://apple.stackexchange.com/questions/427631/xcode13-legacy-build-system-deprecated-unable-to-install-to-device-with-new-b
https://stackoverflow.com/questions/69259866/xcode13-legacy-build-system-deprecated-unable-to-install-to-device-with-new-b

**Comment by keith** [comment]
This likely isn't related to the fix in the other thread, you can normally see more details about why this failed in Console.app, is there anything useful there?

**Comment by OliverKoo** [comment]
Hey Keith, I am sorry I don't work with Xcode a ton. Where is the Console.app? This is what I see in the build log which is not super useful 

```Showing Recent Errors Only

Prepare build
note: Using new build system
note: Planning
unexpected service error: The Xcode build system has crashed. Build again to continue.error: unexpected service error: The Xcode build system has crashed. Build again to continue.


Analyze workspace
Command  failed with a nonzero exit code



Build failed    9/20/21, 5:04 PM    3.2 seconds
```

**Comment by keith** [comment]
/Applications/Utilities/Console.app

**Comment by OliverKoo** [comment]
do you have to download that? this is what I see

```
/Users/okoo$ ls /Applications/Utilities/
Nudge.app Yo.app
```

**Comment by keith** [comment]
Ah something magical about the paths with the new-ish file system setup, you can find it with spotlight or just run `open -a Console`

**Comment by OliverKoo** [comment]
Thanks! This is cool! OK, this is what I see
![Screen Shot 2021-09-21 at 11 51 45 AM](https://user-images.githubusercontent.com/40183324/134230294-b7db99d7-1be3-4b04-904f-d1ff0e2e1108.png)


My intuition is look into iPhone tab on the left?

**Comment by keith** [comment]
Yep, look there, maybe filter but your app name or bundle id, reproduce the issue, and then you should see some more detailed logging

**Comment by OliverKoo** [comment]
ah ok I see it
```
error	11:48:49.268184-0700	installd	unrecognized status -67030 from codesigning library
error	11:48:49.316695-0700	profiled	Assertion retain not supported in async mode
error	11:48:49.407304-0700	SpringBoard	LaunchServices observer: Apps Failed be installed: <private>
error	11:48:49.407466-0700	SpringBoard	Applications did fail to install: (
    "<LSApplicationProxy: 0x28181c240> com.pinterest.enterprise (null) <com.pinterest.enterprise <INVALID >:0>"
) (appInfos: (null))
error	11:48:49.407959-0700	streaming_zip_conduit	Failed to install application at <private> : Error Domain=MIInstallerErrorDomain Code=13 UserInfo={LibMISErrorNumber=-402620415, LegacyErrorString=<private>, SourceFileLine=74, FunctionName=<private>, NSLocalizedDescription=<private>}
error	11:48:49.408010-0700	contextstored	LaunchServices observer: Apps Failed be installed: <private>
```

I will reproduce a successful install and compare it with the failed install logs to see what the difference is

**Comment by keith** [comment]
I think if you google a bit you can get the `<private>` instances to be expanded, that might give more info.

It looks like `-67030` is `errSecCSInfoPlistFailed` https://www.osstatus.com/search/results?platform=all&framework=all&search=67030

Try running `codesign -dvvv path/to/app` to see if it shows more info. It sounds like something is wrong with your plist

**Comment by OliverKoo** [comment]
this problem seems to went away after upgrading to xcode13 RC. we were on 13 beta5. Thanks @keith !
