### ISSUE TITLE
ipa output path changed from bazel-bin to bazel-out/applebin_ios....

### ISSUE THREAD

**Issue by OliverKoo** [bazelbuild/rules_apple#1240]
Hello,

Our org is upgrading rules_apple from 0.20.0 to 0.21.2.

One of our build used to produce `.ipa` file at 
`/execroot/__main__/bazel-out/darwin-opt/bin/ios-app/app.ipa` 
but now it has moved to 
`/execroot/__main__/bazel-out/applebin_ios-ios_arm64-opt-ST-89bcc9a8e0f4/bin/ios-app/app.ipa`

wondering why `darwin-opt` change to `applebin_ios-ios_arm64-opt-ST-89bcc9a8e0f4`?

These threads seem to be related 
https://github.com/bazelbuild/rules_apple/issues/997
https://github.com/bazelbuild/rules_apple/issues/1011
https://github.com/bazelbuild/bazel/issues/12389 
I tried building with `--use_top_level_targets_for_symlinks` and no change.

From @keith 's [comment](https://github.com/bazelbuild/rules_apple/issues/1011#issuecomment-749321842)`applebin_ios-ios_arm64-opt-ST-89bcc9a8e0f4` is generated by Bazel. ~We didn't upgrade our bazel version, wondering why upgrading our rules_apple would change the output path~ (its because 0.21.0 enabled configuration transition). Is there a work around to keep generating `.ipa` under bazel-bin?

**Comment by OliverKoo** [comment]
if I remove the three sequential commit starting from 2da45c802b07074943b9b65cb87ff8523eb3dcad
you can see them [here](https://github.com/bazelbuild/rules_apple/commits/master?after=fcbfcfad2d633b6c8be85954975db88bee3fa26c+279&branch=master ) then `.ipa` file is back to where is was under bazel-bin

**Comment by keith** [comment]
`--use_top_level_targets_for_symlinks` is the only other way around this, but it requires that you're only building targets for the same transition. otherwise you should use the build event protocol file to fetch the specific output paths instead of hardcoding the previous path

**Comment by OliverKoo** [comment]
make sense 👍 . closing this and will use bazelbuild/bazel#12389 to track.

btw @keith I just learned that we are both presenting at the BK conference in November 👋 excited to present with you!

**Comment by keith** [comment]
Another option:

```
% bz cquery --apple_generate_dsym --config=qa RiderApp --starlark:expr="'\n'.join([f.path for f in target.files.to_list()])" --output=starlark

INFO: Invocation ID: fb37b292-26f9-4233-8203-f8589d79ad8c
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/fb37b292-26f9-4233-8203-f8589d79ad8c
INFO: Analyzed target //:RiderApp (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
bazel-out/applebin_ios-ios_x86_64-fastbuild-ST-5cf99f36b64f/bin/Modules/PassengerApp/Lyft.app
bazel-out/applebin_ios-ios_x86_64-fastbuild-ST-5cf99f36b64f/bin/Modules/PassengerApp/Lyft.app.dSYM/Contents/Resources/DWARF/Lyft
bazel-out/applebin_ios-ios_x86_64-fastbuild-ST-5cf99f36b64f/bin/Modules/PassengerApp/Lyft.app.dSYM/Contents/Info.plist
INFO: Elapsed time: 1.129s
INFO: 0 processes.
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/fb37b292-26f9-4233-8203-f8589d79ad8c
INFO: Build completed successfully, 0 total actions
```
