### ISSUE TITLE
Support Alternate Icons in Asset Catalogs (Xcode 13+)

### ISSUE THREAD

**Issue by dflems** [bazelbuild/rules_apple#1261]
https://katzenbaer.medium.com/alternate-app-icons-using-asset-catalogs-in-xcode-13-da6387d1cd78

Xcode 13+ lets you put alternate icons in asset catalogs now. This could be probably be supported by `ios_application` and friends in a backwards compatible way:

```python
ios_application(
    name = "MyApp",
    resources = glob(["CatalogIncludingAlternateIcons.xcassets/**"]),
    appicon_name = "AppIcon",

    # equivalent of ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS
    # pass --include-all-app-icons into actool in Xcode 13+
    # copy all appiconset images into the bundle in Xcode 12 and under
    include_all_appicons = True,

    # equivalent of ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES
    # pass --alternate-app-icon into actool for each one in Xcode 13+
    # copy these appiconsets into the bundle in Xcode 12 and under, exclude others
    alternate_app_icons = ["alticon1", "alticon2"],
)
```

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_apple/pull/1032 ?

**Comment by brentleyjones** [comment]
Asset catalogs being the main difference with Xcode 13+.

**Comment by dflems** [comment]
@keith Being able to use them in asset catalogs is new

**Comment by keith** [comment]
Is the old way still supported for iOS 15+? Or do you have to use this new behavior?

**Comment by dflems** [comment]
@keith I'm not sure. I assume the old way probably still works (copying them into the bundle and referencing them in Info.plist explicitly)

**Comment by wendyliga** [comment]
I create a PR for this [](https://github.com/bazelbuild/rules_apple/issues/1261)
