### ISSUE TITLE
Support for integration test runner

### ISSUE THREAD

**Issue by rahul-malik** [bazelbuild/rules_apple#129]
I'm not sure what exactly needs to be done to make this work or if there is an internal integration test runner that needs to be cleaned up and open-sourced.

The current test runner has an explicit check for `ui` test targets and exits immediately. It's been this way for a while and it would be great to resolve this soon.

**Comment by sergiocampama** [comment]
I'll push for releasing this tomorrow. We have an internal patch submitted which is just missing this push.

**Comment by rahul-malik** [comment]
Thanks @sergiocampama !!! Really looking forward to running our integration tests through Bazel :)

**Comment by rahul-malik** [comment]
Does the internal patch support running tests written with EarlGrey? Since that is a whitebox testing framework we use the unit test (XCTest) rule right now. Also I'm assuming there will be an example with the patch?

**Comment by sergiocampama** [comment]
Not following the "whitebox testing framework" comment. We don't have any examples using EG as it would creep up on our dependencies, but I don't see why it shouldn't work.

The patch will make the new test runner the default, so there's nothing special that you'll need to do, just use `ios_unit_test` or `ios_ui_test` normally. I'll add an example project that showcases the different platforms that we support.

**Comment by rahul-malik** [comment]
@sergiocampama Thanks! The whitebox testing framework was moreso just stipulating that you have to use XCTest with EG since you have access to app internals vs XCUITest where your tests run in a separate process. I'll take a look at the example project when it lands and let you know if i have any questions.

Thanks again!

**Comment by sergiocampama** [comment]
Ok, the change to enable the default runner to use the new test runner for iOS has been released. Can you check against your tests with the latest commit tag? you should not need to specify a `runner` attribute on the tests

**Comment by sergiocampama** [comment]
I've also added a Buttons example with commit https://github.com/bazelbuild/rules_apple/commit/5d2a04027a23294cec41be3b6d9408b332619c79, so check it out :)
