### ISSUE TITLE
Move swift_library into this repository

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#13]
Now that we have a dedicated repository for Apple rules, `swift_library` should be moved here and out of the Bazel repository.

**Comment by keith** [comment]
Are there also plans to support swift sources in other rules in this repository?

**Comment by dmishe** [comment]
Nope, swift_library will be the only compilation rule that allows Swift. That is also true for bazel native rules.

**Comment by allevato** [comment]
And the `swift_library` that is part of Bazel today should work with these rules; just include those libraries among your `deps`.

This issue is merely an organizational one to move Apple-specific .bzl files and tools out of Bazel and into this repository.

**Comment by keith** [comment]
Should I re-open `swift_library` related issues on this repo now? Such as https://github.com/bazelbuild/bazel/issues/2781

**Comment by allevato** [comment]
Yes, that would be best. Thanks!
