### ISSUE TITLE
Rule 'ios_dynamic_framework' cannot be found 

### ISSUE THREAD

**Issue by emad-eldeen** [bazelbuild/rules_apple#1303]
I am trying to build an 'ios_dynamic_framework'. However, I am getting the following error:

```
ine 15, column 50, in <toplevel>
		load("@build_bazel_rules_apple//apple:ios.bzl", "ios_dynamic_framework")
Error: file '@build_bazel_rules_apple//apple:ios.bzl' does not contain symbol 'ios_dynamic_framework' (did you mean 'ios_static_framework'?)
```

Bazel version
```
Bazelisk version: development
Build label: 3.7.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 17:02:20 2020 (1608224540)
Build timestamp: 1608224540
Build timestamp as int: 1608224540
```
I tried 'Bazel clean --expunge' too.
Any idea please what could be the reason?

**Comment by keith** [comment]
What version of rules apple are you using? you probably need to update that. Which might also require a bazel update since you're on an old version

**Comment by emad-eldeen** [comment]
I am actually using the examples in mediapipe. 

The BUILD file is not indicating any version of rules_apple:
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_dynamic_framework")

Can the version be selected manually? And what version should be used?

Thank you.

**Comment by keith** [comment]
Versions are typically defined in the WORKSPACE file. It would be best to update to the latest release, but you might need to file an issue there to make sure everything is compatible with it
