### ISSUE TITLE
A typo in 0.33.0 release note - "-ios_mult_cpus"

### ISSUE THREAD

**Issue by woshimaliang** [bazelbuild/rules_apple#1333]
https://github.com/bazelbuild/rules_apple/releases/tag/0.33.0

pass --ios_mult_cpus=x86_64 should be pass --ios_mult**i**_cpus=x86_64

:)

**Comment by woshimaliang** [comment]
@keith

**Comment by thii** [comment]
Fixed it. Thanks for the report!
