### ISSUE TITLE
Missing Runfiles Location for Test Data

### ISSUE THREAD

**Issue by tinder-cwybranowski** [bazelbuild/rules_apple#1372]
Hello! I'm interested in using the `Runfiles location for test data` feature [described here](https://github.com/bazelbuild/rules_apple/blob/a14ed339739fec4f52527bbcad71203022d7969c/doc/common_info.md#runfiles-location-for-test-data) for `ios_unit_test` targets, however my execution environment never seems to populate the `TEST_SRCDIR` key-value pair as described in the README. Additionally, it doesn't seem like any of the key-value pairs contain a path that leads to artifacts contained within the `ios_unit_test.data` attribute.

I may not be using this feature correctly, so any guidance would be greatly appreciated!

---

## Setup

- Bazel 5.0.0
- Xcode 13.2.1
- rules_apple version 0.33.0

---

## Demo Repository

I've created a public repository that demonstrates this issue: [bazel-runfiles-demo](https://github.com/tinder-cwybranowski/bazel-runfiles-demo).

**Comment by keith** [comment]
Interesting stuff, I don't see how this ever would have worked in the way the doc describes. The test runner doesn't appear to ever have forwarded `TEST_SRCDIR` along to the test itself. Adding something like this in the test runner template script fixes your tests case:

```sh
TEST_ENV="%(test_env)s"
if [[ -n "$TEST_ENV" ]]; then
  TEST_ENV="$TEST_ENV,TEST_SRCDIR=$TEST_SRCDIR"
else
  TEST_ENV="TEST_SRCDIR=$TEST_SRCDIR"
fi
```

**Comment by tinder-cwybranowski** [comment]
> Interesting stuff, I don't see how this ever would have worked in the way the doc describes. The test runner doesn't appear to ever have forwarded `TEST_SRCDIR` along to the test itself. Adding something like this in the test runner template script fixes your tests case:
> 
> ```shell
> TEST_ENV="%(test_env)s"
> if [[ -n "$TEST_ENV" ]]; then
>   TEST_ENV="$TEST_ENV,TEST_SRCDIR=$TEST_SRCDIR"
> else
>   TEST_ENV="TEST_SRCDIR=$TEST_SRCDIR"
> fi
> ```
> 
> In general the iOS simulator test job doesn't inherit the outer environment from bazel itself. Maybe google's internal test runner worked differently at the time they wrote this doc

Really appreciate the quick reply, per usual! So which file exactly did you make that edit to?

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_apple/blob/a14ed339739fec4f52527bbcad71203022d7969c/apple/testing/default_runner/ios_test_runner.template.sh#L101

**Comment by keith** [comment]
If you can try this I'd be interested to hear if you can access resources how you'd expect, I'm not sure what the simulator allows you to do with random file paths on the host system

**Comment by tinder-cwybranowski** [comment]
> If you can try this I'd be interested to hear if you can access resources how you'd expect, I'm not sure what the simulator allows you to do with random file paths on the host system

Absolutely, I'll give this a try tomorrow and circle back! Currently investigating alternatives to ENV injection of host-specific paths for things like snapshots and fixtures.

**Comment by tinder-cwybranowski** [comment]
@keith I can confirm that your aforementioned fix works as expected -- the `TEST_SRCDIR` key-value pair is now non-empty in the execution environment, and further inspection of the path demonstrates that it contains the `ios_unit_test.data` artifact as expected; the relative path to the artifact is `/__main__/DemoLibrary/Data/demo-fixture.txt` when I log it in tests.

This can be seen in practice on [this branch of my demo repository](https://github.com/tinder-cwybranowski/bazel-runfiles-demo/tree/cwybranowski/rules_apple-fix).

I'm still investigating the resource access pattern locally for my use-case, but I'll report back after a bit more digging.

**Comment by keith** [comment]
Yea I'm not surprised you cannot write to there. For snapshots we write to `TEST_UNDECLARED_OUTPUTS_DIR` and collect them outside of bazel back to where we want them.

**Comment by keith** [comment]
Submitted https://github.com/bazelbuild/rules_apple/pull/1379 for setting it in general

**Comment by tinder-cwybranowski** [comment]
> Yea I'm not surprised you cannot write to there. For snapshots we write to `TEST_UNDECLARED_OUTPUTS_DIR` and collect them outside of bazel back to where we want them.

Oh nice, didn't know about `TEST_UNDECLARED_OUTPUTS_DIR` -- I'll definitely look into that.

And I appreciate the PR back to `rules_apple`!

**Comment by keith** [comment]
I find this reference very helpful for this stuff

**Comment by keith** [comment]
https://bazel.build/reference/test-encyclopedia
