### ISSUE TITLE
lipo Thinning unable to find arm64 on apple silicon xcode 13.3

### ISSUE THREAD

**Issue by wendyliga** [bazelbuild/rules_apple#1397]
environment:
- Xcode 13.3
- MacOS 12.3
- min ios 11.0

how to repro
- clone https://github.com/wendyliga/simple_bazel
- `bazel build //ios/DummyApplication`

when using async/await and GroupActivities SDK from apple, `build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.py` will return 2 libs
- /Applications/Xcode_13.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator/libswiftCore.dylib
- /Applications/Xcode_13.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/iphonesimulator/libswift_Concurrency.dylib

but if we check the arch on `libswiftCore.dylib`, It only contains x86_64 and i386.
<details>
  <summary>Spoiler</summary>
<img src="https://user-images.githubusercontent.com/16457495/158939528-d89603dd-f7d0-4495-99fe-b9d14d3872f9.png"/>
</details>

This will make `swift_stdlib_tool.py` unable to thin `arm64`, and will return error
<details>
  <summary>Spoiler</summary>
ERROR: /Users/wendy.liga/Developer/simple_bazel/ios/DummyApplication/BUILD:10:16: SwiftStdlibCopy ios/DummyApplication/DummyApplication-intermediates/swiftlibs failed: (Exit 1): swift_stdlib_tool failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-15bb1cbb5e86/bin/external/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool --platform iphonesimulator --output_path ... (remaining 4 arguments skipped)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-15bb1cbb5e86/bin/external/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.runfiles/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.py", line 132, in <module>
    sys.exit(main())
  File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-15bb1cbb5e86/bin/external/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.runfiles/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.py", line 125, in main
    _lipo_exec_files(stdlib_files, target_archs, args.strip_bitcode, temp_path,
  File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-15bb1cbb5e86/bin/external/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.runfiles/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.py", line 76, in _lipo_exec_files
    lipo.invoke_lipo(
  File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-15bb1cbb5e86/bin/external/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.runfiles/build_bazel_rules_apple/tools/wrapper_common/lipo.py", line 30, in invoke_lipo
    _, stdout, stderr = execute.execute_and_filter_output(cmd,
  File "/private/var/tmp/_bazel_wendy.liga/8284c4a94ccbbb579b9e33d50d39273c/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-15bb1cbb5e86/bin/external/build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.runfiles/build_bazel_rules_apple/tools/wrapper_common/execute.py", line 103, in execute_and_filter_output
    raise subprocess.CalledProcessError(proc.returncode, cmd_args)
subprocess.CalledProcessError: Command '['xcrun', 'lipo', '/var/folders/tg/5hc1y5wn5qg4gnfhktnyt_kc0000gn/T/swift_stdlib_tool.XXXXXXxz_7yy93/libswiftCore.dylib', '-output', 'bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-3804fa44a325/bin/ios/DummyApplication/DummyApplication-intermediates/swiftlibs/libswiftCore.dylib']' returned non-zero exit status 1.
ERROR:

error: /Applications/Xcode_13.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: one of -create, -thin <arch_type>, -extract <arch_type>, -remove <arch_type>, -replace <arch_type> <file_name>, -verify_arch <arch_type> ... , -archs, -info, or -detailed_info must be specified
usage: lipo <input_file> <command> [<options> ...]
  command is one of:
    -archs
    -create
    -detailed_info
    -extract <arch_type> [-extract <arch_type> ...]
    -extract_family <arch_type> [-extract_family <arch_type> ...]
    -info
    -remove <arch_type> [-remove <arch_type> ...]
    -replace <arch_type> <file_name> [-replace <arch_type> <file_name> ...]
    -thin <arch_type>
    -verify_arch <arch_type> ...
  options are one or more of:
    -arch <arch_type> <input_file>
    -hideARM64
    -output <output_file>
    -segalign <arch_type> <alignment>

Target //ios/DummyApplication:DummyApplication failed to build
Use --verbose_failures to see the command lines of failed build steps.
</details>

is this xcode 13.3' issues ?

**Comment by wendyliga** [comment]
using rosetta on Xcode and simulator seem to solve the issue, but this means we can't build a native apple silicon binary.

**Comment by thii** [comment]
It's because of https://bugs.swift.org/browse/SR-16010, I have a workaround for it here https://github.com/bazelbuild/rules_apple/pull/1396.

**Comment by wendyliga** [comment]
@thii use the latest master, the dylib still has only 2 arches(i386, x86_64)
`build_bazel_rules_apple/tools/swift_stdlib_tool/swift_stdlib_tool.py` will generate this command for `_copy_swift_stdlibs`
```
xcrun swift-stdlib-tool --copy --platform iphonesimulator --destination /var/folders/tg/5hc1y5wn5qg4gnfhktnyt_kc0000gn/T/swift_stdlib_tool.XXXXXXehflna8n --source-libraries /Applications/Xcode_13.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/iphonesimulator --source-libraries /Applications/Xcode_13.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator --scan-executable bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-3804fa44a325/bin/ios/DummyApplication/DummyApplication_lipobin
```

if we use `--print` instead of `--copy` the output will be 
![Screen Shot 2022-03-21 at 10 06 25](https://user-images.githubusercontent.com/16457495/159200205-d8bc300d-db01-42f4-908b-cb48a3cd1025.png)

so after the change, it still refers to the same `dylib` that doesn't have arm64 binary

**Comment by thii** [comment]
What's your app's deployment target?

**Comment by wendyliga** [comment]
@thii do you mean `minimum_os_version`? it's 11.0
https://github.com/wendyliga/simple_bazel/blob/master/ios/DummyApplication/BUILD

**Comment by wendyliga** [comment]
below `minimum_os_version` 13.0, `swift-stdlib-tool` will always return `swift-5.0/iphonesimulator/libswiftCore.dylib`

the issue seems to be if only below 13.0

**Comment by thii** [comment]
I forgot the case where you can have your app and extensions target different OS versions.

**Comment by wendyliga** [comment]
https://github.com/bazelbuild/rules_apple/pull/1400 solve the issue, thanks @thii
