### ISSUE TITLE
Generate Swift source for CoreML models

### ISSUE THREAD

**Issue by a2** [bazelbuild/rules_apple#1418]
(I'm interested in working on Swift source generation for CoreML models. I saw in the [contributing guidelines](https://github.com/bazelbuild/rules_apple/blob/a93ad60b28877b0cfa16abafc6bdd3fce0e66c76/CONTRIBUTING.md) that I should file an issue to "claim" this work item.)

I noticed that the `coremlc generate` subcommand now — at least as of version 1127.100.30, which comes bundled with Xcode 13.3 — supports generating Swift source files with the public access modifiers (`--public-access`):

<details>
<summary>Output from <code>xcrun coremlc generate --help</code></summary>

```
$ xcrun coremlc generate --help
usage: coremlc <command> <inputdocument> <outputpath> [options ...]

Examples:

[...]

Commands:

[...]

   generate <model.{mlmodel,mlpackage}> </desired/path/to/output/directory>
      Generate source code interface for supplied CoreML .mlmodel or .mlpackage with the following options:
      --outputpath </desired/path/to/output/directory> : where to place the generated interface files.
      --language <Swift|Objective-C> : interface language.
      --swift-version x.y : generated interface requires Swift version x.y (swift only).
      --public-access : classes and members get public access specifier (swift only).
      --globalmodule : generate objc compatible model classes (swift only).
      --sdkroot : filename base for System/Library/CoreServices/SystemVersion.plist (internal, swift only). Requires --platform.
      --platform <macos|ios|watchos|tvos|maccatalyst> : check mlmodel version compatability for this platform.
      --deployment-target xx.yy.zz : check mlmodel version compatability for this version.
      --container <bundle-resources|swift-package> : code generation variants (internal).
      --no-documentation : suppress inline documentation.
      --dry-run : don't write generated code to output directory.

[...]
```
</details>

As for implementing this, and because naming is one of the two most difficult problems in programming (along with cache invalidation and off-by-one errors), I see that there is are `objc_intent_library` and `swift_intent_library` functions (Macros? I'm new to Bazel) in [_apple/resources.bzl_](https://github.com/bazelbuild/rules_apple/blob/a93ad60b28877b0cfa16abafc6bdd3fce0e66c76/apple/resources.bzl).

Should `apple_core_ml_library` be renamed to something like `objc_apple_core_ml_library` to make room for `swift_apple_core_ml_library`?

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_apple/pull/1419
