### ISSUE TITLE
apple/testing/default_host/ios fails to build

### ISSUE THREAD

**Issue by shoumikhin** [bazelbuild/rules_apple#142]
See the job log at https://travis-ci.org/google/promises/jobs/346222548
Previous build https://travis-ci.org/google/promises/builds/344875298 issued 4 days ago was successful.

**Comment by thomasvl** [comment]
What bazel version are you using?

**Comment by shoumikhin** [comment]
$ bazel version
Build label: 0.11.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun May 1 04:50:25 +50118 (1519414519825)
Build timestamp: 1519414519825
Build timestamp as int: 1519414519825

Rules are here https://raw.githubusercontent.com/google/promises/master/WORKSPACE

**Comment by thomasvl** [comment]
Looking at your [WORKSPACE](https://github.com/google/promises/blob/master/WORKSPACE), aren't you using a pinned release of the rules?  (0.2.0)  So this isn't related to a change on our end, but more likely to moving to a newer bazel release that doesn't support that release of the rules.

**Comment by sergiocampama** [comment]
can you set this in your WORKSPACE instead?

```
git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    commit = "fc6143018161b934e6830c1cf7688200a10e4963",
)
```

**Comment by thomasvl** [comment]
Fyi - @allevato just did a [0.3.0 release](https://github.com/bazelbuild/rules_apple/releases/tag/0.3.0) to provide a tag you should be able to switch too.  Please see the release notes about what is needed to adopt it.

**Comment by shoumikhin** [comment]
Yeah, looks like Bazel was updated in Homebrew: it used to be 0.10.1, and now it's 0.11.0.
For the following WORKSPACE:

```
http_archive(
    name = "build_bazel_rules_apple",
    strip_prefix = "rules_apple-0.3.0",
    urls = ["https://github.com/bazelbuild/rules_apple/archive/0.3.0.tar.gz"],
)
```

I get this:

```sh
$ bazel test Tests
ERROR: Skipping 'Tests': error loading package '': Extension file not found. Unable to load package for '@bazel_skylib//lib:collections.bzl': The repository could not be resolved
ERROR: error loading package '': Extension file not found. Unable to load package for '@bazel_skylib//lib:collections.bzl': The repository could not be resolved
INFO: Elapsed time: 0.127s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:
ERROR: Couldn't start the build. Unable to run tests
```

Can't downgrade Bazel, though:

```sh
$ brew install bazel@0.10.1
Error: No available formula with the name "bazel@0.10.1"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by sergiocampama** [comment]
You're missing the skylib dependency that needs to be added to the WORKSPACE as well. Add
```
git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
    tag = "0.2.0",
)
```

**Comment by thomasvl** [comment]
That's the part where I said please see the release notes for that release.  :)

**Comment by shoumikhin** [comment]
Gotcha, thanks!
Everything worked with the right WORKSPACE.
