### ISSUE TITLE
DocC Rule

### ISSUE THREAD

**Issue by wendyliga** [bazelbuild/rules_apple#1420]
Will like to request to add a rule to generate apple's DocC documentation.
I would like to contribute it myself, but I am having a hard time translating it to starlark and bazel rule

but I would love to contribute on how to produce it

# Emit symbol graph by passing to swift library
```
copts = [
   '-Xfrontend',
   '-emit-symbol-graph',
   '-emit-symbol-graph-dir',
   '/var/tmp/swift-symbol-graph/arm64-apple-ios-simulator'
]
```

# Generate Docc
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc \
convert \
--index \
--fallback-display-name \
MySwiftLibrary \
--fallback-bundle-identifier \
com.example.MySwiftLibrary \
--fallback-bundle-version \
1 \
--output-dir \
/var/tmp/generated.doccarchive \
--additional-symbol-graph-dir \
/var/tmp/swift-symbol-graph
```

DocC is also open-sourced by apple, this is also possible to achieve by https://github.com/apple/swift-docc#using-docc-to-build-and-preview-documentation

**Comment by wendyliga** [comment]
maybe to achieve this, we need to add a new parameter on swift_library like `generate_symbol_graph`,

if true, then we will append copts, declare the file, and pass it to the provider, so the rule we create on rules_apple will require user to pass the swift_library, so we could access the symbol graph json

**Comment by tinder-maxwellelliott** [comment]
I am also interested in such a rule. I can also start to investigate this

**Comment by jpsim** [comment]
With https://github.com/bazelbuild/rules_swift/pull/838, you'll be able to emit the symbol graph for a `swift_library` by adding `features = ["swift.emit_symbol_graph"]`.

**Comment by louwers** [comment]
Does someone know how this can be achieved with `rules_xcodeproj` & `xcodebuild` in the meantime?

**Comment by luispadron** [comment]
Started really basic support for this over in #2007

**Comment by louwers** [comment]
Can we create a new issue for Objective-C support?

**Comment by luispadron** [comment]
https://github.com/bazelbuild/rules_apple/issues/2241
