### ISSUE TITLE
XCFramework for macOS

### ISSUE THREAD

**Issue by yuriyhanysh** [bazelbuild/rules_apple#1475]
Hello!
Is there a way to create XCFramework for both iOS and macOS using `apple_xcframework`?
`minimum_deployment_os_versions` and `minimum_os_versions` attributes don't seem to work. And `ios` attribute allows you to specify only `ios` architectures.

**Comment by xiemotongye** [comment]
Is there a follow-up?
I'm now facing a same issue.

**Comment by luispadron** [comment]
I'd also like this so if anyone is already working on this let me know otherwise I'll likely spend some time to get this working for macOS

**Comment by luispadron** [comment]
Started looking into this a bit and I believe the issue might be in Bazel core, given:

```python
apple_xcframework(
    name = "ios_and_macos_dynamic_xcframework",
    bundle_id = "com.google.example",
    extension_safe = True,
    infoplists = [
        "//test/starlark_tests/resources:Info.plist",
    ],
    ios = {
        "simulator": ["x86_64"],
        "device": ["arm64"],
    },
    minimum_os_versions = {
        "ios": common.min_os_ios.baseline,
        "macos": common.min_os_macos.baseline,
    },
    public_hdrs = [
        "//test/starlark_tests/resources:shared.h",
    ],
    tags = common.fixture_tags,
    deps = [":fmwk_lib"],
)
```

I get the following output when examining the [split transition keys used here](https://github.com/bazelbuild/bazel/blob/ff63e0d0499d6d0ac82dcd3e58935f8718bd46f3/src/main/starlark/builtins_bzl/common/objc/linking_support.bzl#L213C50-L213C85):

```
Error in fail: [("ios_arm64_device", <target //apple:default_cc_toolchain_forwarder>), ("ios_x86_64_simulator", <target //apple:default_cc_toolchain_forwarder>)]
```

**Comment by luispadron** [comment]
I've got something in draft now that generates the expected XCFramework: https://github.com/bazelbuild/rules_apple/pull/2459
