### ISSUE TITLE
Support compiling texture atlases

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#15]
When Xcode sees a `.atlas` folder in a project, it automatically runs the `TextureAtlas` tool on it. It doesn't pass any special arguments, however (you can run `xcrun TextureAtlas` with no arguments to see what it accepts).

Our rules should look at doing the same. We can support texture atlases in two ways:

1. Detect `.atlas` folders during resource processing and do what Xcode does
1. Add an `apple_texture_atlas` rule that provides the full set of command options as attributes, separately compiles a `.atlas` into a `.atlasc`, and propagates that via the `AppleResource` provider. The resource processor will see `.atlasc` as an unrecognized type and simply copy it into the bundle verbatim.

**Comment by sergiocampama** [comment]
Fixed with the new bundling implementation
