### ISSUE TITLE
Can't compile with '-swift-version 4'

### ISSUE THREAD

**Issue by jdelfino** [bazelbuild/rules_apple#160]
I'm trying to compile a Swift 4 swift_lib, but there always seems to be a '-swift-version 3' in the build command.

Minimal project that has this issue can be found here: https://github.com/jdelfino/bazel_swift4

In particular, here is my BUILD file:

```
load("@build_bazel_rules_apple//apple:swift.bzl", "swift_library")

swift_library(
    name = "test_lib",
    srcs = [
      ":Test.swift",
    ],
    copts = ["-swift-version", "4"]
)
```

Clone, then 'bazel build test_lib -s':

Gives the output below. Note the "-swift-version 4 -swift-version 3". -swift-version 4 was added by the copts in my rule, but I can't seem to figure out where -swift-version 3 is coming from or how to suppress it, and the last version in the command wins. Is this a bug, or am I doing something wrong?

INFO: Analysed target //:test_lib (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //:test_lib [action 'Compiling Swift module test_lib (1 files)']
(cd /private/var/tmp/_bazel_jdelfino/ee58b326ca18eb2bab819995ca66a754/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=11.2 \
    XCODE_VERSION_OVERRIDE=9.2.0 \
  bazel-out/host/bin/external/bazel_tools/tools/objc/xcrunwrapper swiftc -emit-object -module-name test_lib -target x86_64-apple-ios11.2 -sdk __BAZEL_XCODE_SDKROOT__ -module-cache-path bazel-out/darwin-fastbuild/genfiles/_objc_module_cache -Onone -DDEBUG -enable-testing -Xfrontend -serialize-debugging-options -parse-as-library Test.swift -Ibazel-out/darwin-fastbuild/genfiles -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -Xcc -iquote -Xcc . -Xcc -O0 -Xcc '-DDEBUG=1' **-swift-version 4 -swift-version 3** -Ibazel-out/darwin-fastbuild/genfiles/test_lib/_objs -emit-module-path bazel-out/darwin-fastbuild/genfiles/test_lib/_objs/test_lib.swiftmodule -emit-objc-header-path bazel-out/darwin-fastbuild/genfiles/test_lib-Swift.h -output-file-map bazel-out/darwin-fastbuild/genfiles/test_lib.output_file_map.json)
ERROR: /canopy/dumb_swift/BUILD:3:1: Compiling Swift module test_lib (1 files) failed (Exit 1)
Test.swift:4:64: error: type 'UIFontWeight' (aka 'CGFloat') has no member 'semibold'
    static var font = UIFont.systemFont(ofSize: 20.0, weight: .semibold)
                                                              ~^
Target //:test_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.444s, Critical Path: 2.31s
FAILED: Build did NOT complete successfully

**Comment by sergiocampama** [comment]
After version 0.3.0 the semantics of Swift version processing have changed, but we haven't made a new release yet. 

Would you mind using rules_apple from the latest commit instead? adc96e1667416502ca87ccf888b6612821b37a3d should work.

We're also working on improving the release system, but it will take us some time to get there

**Comment by jdelfino** [comment]
Thanks @sergiocampama, switching to use adc96e1 for rules_apple worked! Will leave it to you if you want to close this out now or wait for a release.

**Comment by allevato** [comment]
This change has now been rolled out in [0.4.0](https://github.com/bazelbuild/rules_apple/releases/tag/0.4.0). Thanks!
