### ISSUE TITLE
Add documentation for `provisioning_profile` attr of `ios_unit_test`

### ISSUE THREAD

**Issue by kkpattern** [bazelbuild/rules_apple#1617]
For an `ios_unit_test` to run on a real device, the `provisioning_profile` needs to be set. However, the documentation of `ios_unit_test` doesn't mention this. Some users may not know about this. https://github.com/bazelbuild/tulsi/issues/266 . 

If it's ok, I'd like to create a PR. But I don't know if any other attrs need to be mentioned. For our project, the `provisioning_profile` is the only one required.

**Comment by keith** [comment]
Documenting this would be great, I don't think others are required

**Comment by kkpattern** [comment]
Cool. Does `ios_ui_test` also require `provisioning_profile` to run on a real device? I assume that's the case, but we don't have UI tests, so I can't verify it. If needed I can also add documentation for `ios_ui_test`.

**Comment by keith** [comment]
Yep I think they are needed for anything on device
