### ISSUE TITLE
--apple_bitcode flag ineffective on iOS targets

### ISSUE THREAD

**Issue by th0br0** [bazelbuild/rules_apple#163]
When creating an `apple_static_library` target like [1] and building this via `bazel build --apple_bitcode=embedded --ios_multi_cpus=arm64 -c opt //:myappletarget` the bitcode is not being included in the actual build causing issues when trying to run the code on-device similar to:

```
/Project/myapplelibrary.a(lib1.o) does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

However, specifying `--copt=-fembed-bitcode` causes a conflict with the `-fdata-sections` and `-ffunction-sections` flags that bazel uses by default.

How can this be resolved? Is there some way I can resolve this temporarily?

The references to `b/73546952` and `b/35091927` at https://github.com/bazelbuild/rules_apple/blob/master/test/ios_application_test.sh#L838 and https://github.com/bazelbuild/rules_apple/blob/master/test/configurations.bzl#L21 make me believe you're tracking this issue internally already?

[1]
```
cc_library(
  name="mynativedependency"],
  srcs=["lib1.c"], hdrs=["lib1.h"])

apple_static_library(
    name="myappletarget",
    deps=[":mynativedependency"],
    platform_type="ios",
    minimum_os_version="9.0",
    visibility = ["//visibility:public"])
```

**Comment by sergiocampama** [comment]
Hi @th0br0, we are indeed tracking this issue for the OSS crosstool in bazel for Apple builds. Feel free to create an issue in bazel. We are hoping to have this resolved soon

**Comment by alexsporn** [comment]
Dropping `-c opt` from the build command will build a correct static library containing valid bitcode.

**Comment by rajivshah3** [comment]
It seems like if you do `bazel build --ios_multi_cpus=arm64 --copt=-fembed-bitcode --copt=-Ofast //:myappletarget` it will compile with valid bitcode and optimize it

**Comment by keith** [comment]
This workaround is fine for building standalone libraries, but if you need to build an app with bitcode it seems we need this change https://github.com/bazelbuild/bazel/pull/7356

**Comment by rajivshah3** [comment]
The flag conflict should be fixed in https://github.com/bazelbuild/bazel/pull/7623

**Comment by sergiocampama** [comment]
Let's revisit this when bazel 0.24 is out to see if it's solved

**Comment by keith** [comment]
0.24.0 was just released, this should be fixed there

**Comment by keith** [comment]
This can be closed
