### ISSUE TITLE
Bazel platforms support

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#1658]
This is a tracking issue for supporting bazel's platforms for rules_apple. When relevant issues come up it would be useful to link them here for context.

**Comment by keith** [comment]
Related:

- https://github.com/bazelbuild/rules_apple/issues/1650
- https://github.com/bazelbuild/bazel/issues/15041

**Comment by jiawen** [comment]
We should author a "state of affairs" document for building Apple apps, covering macOS, iOS, and tvOS. Especially relevant to my use case are how multiarch binaries and libraries interact with platforms, and the sharp edges the remain when it comes to `objc_library` vs `cc_library` and `swift_library`. Ideally, this document would include what we imagine the ideal state should be wrt platforms and a roadmap for getting there (e.g., using [platform mappings](https://bazel.build/concepts/platforms#platform-mappings)).

**Comment by louwers** [comment]
Oops. I have been trying to debug why my platform constraint variables weren't propagated. Turns out there was a `ios_application` in the dependency tree. 😅

**Comment by keith** [comment]
In general platforms are supported at this point. You don't need a platform_mappings and with bazel 7.x + the new [apple_support toolchain](https://github.com/bazelbuild/apple_support/#toolchain-setup) everything should work as expected. If you find otherwise please file an issue!

**Comment by jiawen** [comment]
This is fantastic - a major milestone!

Quick question / suggestion wrt [apple_support_toolchain/README.md](https://github.com/bazelbuild/apple_support/#toolchain-setup). When it says

> To use the Apple CC toolchain, pull this repository into your build and add this to your .bazelrc:

Does this still apply with Bazel 7?

Additionally, when the instructions say to add

> `build:macos --apple_crosstool_top=@local_config_apple_cc//:toolchain` to `.bazelrc`

does that mean in general, users should pass `--config=macos` on the command line (or pass [--enable_platform_specific_config](https://bazel.build/reference/command-line-reference#flag--enable_platform_specific_config)?

**Comment by jiawen** [comment]
Amazing work as always, thanks!

**Comment by kkpattern** [comment]
Thanks for the awesome work. We are planning migrate our multi-platform(iOS, Android, Linux, Windows) project to platforms. The bazel [doc](https://bazel.build/concepts/platforms#apple) says "Apple rules do not support platforms and are not yet scheduled for support". Is this an outdated doc? Because according to this issue, `rules_apple` already support platforms.

**Comment by keith** [comment]
I've lost track of all the details here, in general things should work in the golden path, but some things get complex when you try building a single platform agnostic library for different platforms.

**Comment by kkpattern** [comment]
Thanks. We will give it a try. Maybe we can send a PR to update the doc according to the result.
