### ISSUE TITLE
apple_xcframework rule causes “could not inspect application package” when added to Xcode App

### ISSUE THREAD

**Issue by shreyash-sharechat** [bazelbuild/rules_apple#1700]
I'm building MediaPipe based face recognition lib using Bazel, I'm using [apple_xcframework](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md) bazel rule.

This creates a dynamic xcframework, which I then share to other devs who add it to their XCode projects (Apps). They do this by adding my xcframework to their app target and setting `embed & sign` since it is dynamic framework.

**Issue:** Everything builds fine but when app starts to get installed on device they get this error:

    could not inspect application package

Initial research concluded in manually resigning my xframework with app devs' signature as mentioned [here](https://stackoverflow.com/a/26197853/6709940). But it doesn't work.

What else I'm missing here?

**Comment by shreyash-sharechat** [comment]
I have finally figured this out, 
In the bazel rule, I had missed mentioning `bundle_id`, once I add it as a parameter to [apple_xcframework](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md) rule and also (optional) add it in the `info.plist` file it worked.

This has solved my issue. Its clearly dev mistake but for some reason bazel doensn't throw an error even though `bundle_id` is missing (which is infact a `required` param).

**Comment by brentleyjones** [comment]
We should make sure developers have to set the `bundle_id`.

**Comment by keith** [comment]
Fixed by https://github.com/bazelbuild/rules_apple/commit/dc9082008588e190108ddeea15e0d56353928227 which will be in the 2.x release, but you can cherry pick into the 5.x release if you'd like
