### ISSUE TITLE
Add strip_prefix_header to objc_library rule

### ISSUE THREAD

**Issue by ob** [bazelbuild/rules_apple#173]
I'm trying to add an external dependency ([OCHamcrest](https://github.com/hamcrest/OCHamcrest)) which has all of its includes as:

```
#include <OCHamcrest/Foo.h>
```

I was trying to remove the `OCHamcrest` prefix in my `objc_library` rule, but found it has no support for it. Is there another way of stripping the prefix without having to modify all files?

**Comment by thomasvl** [comment]
objc_library is currently a native rule in bazel, so you'll want to open this against bazel.

At some point in the future we may look at moving objc_library to skylark and bundling it here, but that isn't current something that I think anyone is looking at.

**Comment by ob** [comment]
After doing some digging, I think https://github.com/bazelbuild/bazel/pull/3712 is a better way. Closing this.
