### ISSUE TITLE
clonefile fails if source and destination are on different disk volumes

### ISSUE THREAD

**Issue by G-200** [bazelbuild/rules_apple#1736]
https://github.com/bazelbuild/rules_apple/blob/f9dbf82f43082dcbd2a97ce2281b0d9acbe16f9c/tools/bundletool/bundletool_experimental.py#L217

Probably should fall back to plain copy in this case?

**Comment by keith** [comment]
Can you test with https://github.com/bazelbuild/rules_apple/pull/1737

**Comment by keith** [comment]
oh right, I updated the PR

**Comment by keith** [comment]
Pushed another change that fixed in my testing, hopefully last try!

**Comment by keith** [comment]
Thanks for testing it, merged!
