### ISSUE TITLE
Extend coverage to allow filtering of sources

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#1759]
Currently `$COVERAGE_MANIFEST` includes everything under `--instrumentation_filter`. In the case you want to be strict about "only a target's direct test should be considered for its coverage" this file includes to much. We should add an attribute to unit test targets to allow filtering more specifically, then users can pass whatever files they want, potentially with a genrule

@maxwellE is going to work on this

**Comment by maxwellE** [comment]
Working on this now
