### ISSUE TITLE
ios_static_framework does not have infoplist

### ISSUE THREAD

**Issue by balazsbanyai** [bazelbuild/rules_apple#176]
Frameworks generated by the ios_static_framework rule does not have the option to define an info plist, therefore there is no such file in the output framework. The created framework is not working properly in an xcode project, because the missing info.plist.

Expected behavior
The ios_static_framework should provide an option to define the info plist.

**Comment by balazsbanyai** [comment]
Sure,

So my isse here is that if I build a framework using the
ios_static_framework, there will be no infoplist generated in the output
framework.
I want to use this framework directly from another xcode project, and I can
add it as an embedded framework to the consumer project, code against the
headers, compile, but the built application can not be deployed to any
device nor emulator, since it is not allowed to embed a framework without
plist in it.

When I copy an infoplist manually into the framework, it works seamlessly.

The ios_framework does have the option to define an infoplist, and that
works as expected, but that one doesn't generate a module map, which is
also required to consume the framework properly.

Did this explanation clarify the issue i'm facing?

**Comment by thomasvl** [comment]
A static framework should never be an "embedded" framework in the final bundle, you actually need it to get linked into the binary going into the bundle.

**Comment by balazsbanyai** [comment]
Without embedding the framework, I was able to get it working, thank you very much. XCode still complains about "non-modular import in header..." so I needed to delete the moduleMap manually, but it works! Thank you very much!

**Comment by steeve** [comment]
I think this is a valid request, though. Build tools such as Carthage rely on the `Info.plist` being there to recognise versions.
We actually generate one via a post processing script.

**Comment by steeve** [comment]
In case somebody stumbles upon this, here is how we do it, with stamping support:
```python
ios_static_framework(
...
    ipa_post_processor = ":plist_generate",
...
)

sh_binary(
    name = "plist_generate",
    srcs = ["plist_generate.sh"],
    visibility = ["//visibility:public"],
)
```

`plist_generate.sh`:
```sh
#!/bin/bash

set -euo pipefail

archive_root_path=${1}
framework_path=$(find ${archive_root_path} -type d -name '*.framework')
framework_name=$(basename ${framework_path%.framework*})

# Read the stamps to get the version
eval $(cat bazel-out/stable-status.txt bazel-out/volatile-status.txt | sed 's/ /=/')

plutil -convert binary1 -o "${framework_path}/Info.plist" - <<EOF
{
    "CFBundleExecutable": "${framework_name}",
    "CFBundlePackageType": "FMWK",
    "CFBundleShortVersionString": "${STABLE_CORE_VERSION}",
    "MinimumOSVersion": "10.0",
    "CFBundleSupportedPlatforms": [
        "iPhoneOS",
        "iPhoneSimulator",
    ],
}
EOF
```

**Comment by sergiocampama** [comment]
I was going to comment, that's a specific integration for Carthage, so an `ipa_post_processor` sounds like the way to go

**Comment by steeve** [comment]
The following diff on rules_apple would probably work, but would then make `Info.plist` and `bundle_id` mandatory:
```diff
diff --git a/apple/internal/ios_rules.bzl b/apple/internal/ios_rules.bzl
index 0aff40b..063248c 100644
--- a/apple/internal/ios_rules.bzl
+++ b/apple/internal/ios_rules.bzl
@@ -297,8 +297,10 @@ def _ios_static_framework_impl(ctx):
     binary_target = ctx.attr.deps[0]
     binary_artifact = binary_target[apple_common.AppleStaticLibrary].archive

+    bundle_id = ctx.attr.bundle_id
+
     processor_partials = [
-        partials.apple_bundle_info_partial(),
+        partials.apple_bundle_info_partial(bundle_id = bundle_id),
         partials.binary_partial(binary_artifact = binary_artifact),
         partials.framework_header_modulemap_partial(
             hdrs = ctx.files.hdrs,
diff --git a/apple/internal/rule_support.bzl b/apple/internal/rule_support.bzl
index 9489007..93a24be 100644
--- a/apple/internal/rule_support.bzl
+++ b/apple/internal/rule_support.bzl
@@ -231,9 +231,9 @@ _RULE_TYPE_DESCRIPTORS = {
         apple_product_type.static_framework: _describe_rule_type(
             allowed_device_families = ["iphone", "ipad"],
             bundle_extension = ".framework",
-            has_infoplist = False,
+            has_infoplist = True,
             product_type = apple_product_type.static_framework,
-            requires_bundle_id = False,
+            requires_bundle_id = True,
             requires_provisioning_profile = False,
             skip_signing = True,
         ),
```
