### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break rules_apple in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/rules_apple#1787]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking rules_apple. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e3a0-4130-9e31-559041f94a4e)
- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-e3a3-487d-8c6e-bfe2b35f8b40)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by keith** [comment]
subar is the failure here, blocked on xctestrunner

**Comment by keertk** [comment]
Thanks!
No longer seeing these errors - closing.
