### ISSUE TITLE
local_provisioning_profile implicitly depends upon the target '@local_provisioning_profiles//:fallback_profiles'

### ISSUE THREAD

**Issue by AttilaTheFun** [bazelbuild/rules_apple#1816]
Hi folks! After successfully uploading a version of my app with a hardcoded path to a provisioning profile, I'm trying to get automatic detection of local profiles working.

I tried to follow the example for local_provisioning_profile here: https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#local_provisioning_profile

My BUILD file looks like this:
```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@build_bazel_rules_apple//apple:apple.bzl", "local_provisioning_profile")
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
load("@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:defs.bzl", "top_level_target", "xcodeproj")

# Assets

filegroup(
    name = "AppIcon.xcassets",
    srcs = glob(["Resources/AppIcon.xcassets/**"]),
)

filegroup(
    name = "Assets.xcassets",
    srcs = glob(["Resources/Assets.xcassets/**"]),
)

# Sources

swift_library(
    name = "Sources",
    module_name = "Stetho",
    srcs = glob([
        "Sources/*.swift",
    ]),
    data = [
        "Resources/Main.storyboard",
        "Resources/LaunchScreen.storyboard",
    ],
    deps = [
        "@swiftpkg_kingfisher//:Sources_Kingfisher",
        "@swiftpkg_spotifywebapi//:Sources_SpotifyWebAPI",
    ],
)

# Provisioning Profiles

local_provisioning_profile(
    name = "DevelopmentProfile",
    profile_name = "Stetho Development",
    team_id = "B86E5YKCTK",
)

local_provisioning_profile(
    name = "DistributionProfile",
    profile_name = "Stetho Distribution",
    team_id = "B86E5YKCTK",
)

# Applications

BUNDLE_ID = "com.Aphelion.Stetho"
BUNDLE_NAME = "Stetho"
INFOPLISTS = [":Info.plist"]
MINIMUM_OS_VERSION = "15.0"
FAMILIES = ["iphone"]
APP_ICONS = [":AppIcon.xcassets"]
RESOURCES = [":AppIcon.xcassets"]
DEPS = [":Sources"]

ios_application(
    name = "Stetho",
    bundle_id = BUNDLE_ID,
    bundle_name = BUNDLE_NAME,
    infoplists = INFOPLISTS,
    provisioning_profile = ":DevelopmentProfile",
    minimum_os_version = MINIMUM_OS_VERSION,
    families = FAMILIES,
    app_icons = APP_ICONS,
    resources = RESOURCES,
    deps = DEPS,
)

ios_application(
    name = "StethoRelease",
    bundle_id = BUNDLE_ID,
    bundle_name = BUNDLE_NAME,
    infoplists = INFOPLISTS,
    provisioning_profile = ":DistributionProfile",
    minimum_os_version = MINIMUM_OS_VERSION,
    families = FAMILIES,
    app_icons = APP_ICONS,
    resources = RESOURCES,
    deps = DEPS,
)
```

Both of these provisioning profiles exist under `~/Library/MobileDevice/Provisioning Profiles`

But when I try to run:
```
bazel build //Stetho
```

I get the error:
```
logan@Logans-MBP Stetho % bazel build //Stetho
ERROR: /Users/logan/Developer/Swift/Apps/Stetho/Stetho/BUILD:38:27: every rule of type local_provisioning_profile implicitly depends upon the target '@local_provisioning_profiles//:fallback_profiles', but this target could not be found because of: no such package '@local_provisioning_profiles//': The repository '@local_provisioning_profiles' could not be resolved: Repository '@local_provisioning_profiles' is not defined
ERROR: /Users/logan/Developer/Swift/Apps/Stetho/Stetho/BUILD:38:27: every rule of type local_provisioning_profile implicitly depends upon the target '@local_provisioning_profiles//:profiles', but this target could not be found because of: no such package '@local_provisioning_profiles//': The repository '@local_provisioning_profiles' could not be resolved: Repository '@local_provisioning_profiles' is not defined
ERROR: Analysis of target '//Stetho:Stetho' failed; build aborted: 
INFO: Elapsed time: 0.056s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 1 target configured)
```

The docs say the fallback profiles are optional. Is that not the case? And if not, how would I add them? Thanks!

**Comment by brentleyjones** [comment]
You'll need to adjust your `WORKSPACE` per this: https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#in-your-workspace-file

**Comment by AttilaTheFun** [comment]
Ah it was not clear to me from the docs that the local_provisioning_profiles required a provisioning_profile_repository. Let me see if that fixes it.

**Comment by AttilaTheFun** [comment]
Okay @brentleyjones that seemed to work. One other thing I was wondering re: provisioning profiles is whether there is a way to make the ios_application rule automatically select the development / distribution certificate? I saw in the example here they had separate release and development versions of the app.
https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#local_provisioning_profile

That feels like a hassle -- I would rather just have one version I pass an environment variable / some other flag to for development / release builds. It also resulted in my release IPA having a different name (StethoRelease) than the regular one which could complicate things. I guess I could make an IPA modifier to rename it but that also feels like a hassle.

**Comment by AttilaTheFun** [comment]
Ah maybe I could use a select(...) with a config_setting for that?

**Comment by brentleyjones** [comment]
Yes, you should use `select()`: https://github.com/buildbuddy-io/rules_xcodeproj/blob/c11eddaa210aabc26c7756c52c3bcca7f0c19bb9/examples/integration/iOSApp/Source/BUILD#L54-L57

**Comment by AttilaTheFun** [comment]
Ah hmm it looks like they're doing basically what I did with:
```
config_setting(
    name = "release_build",
    values = {
        "compilation_mode": "opt",
    },
)
```
Is there a way to use an environment variable instead because an optimized build is not necessarily intended for release.

**Comment by brentleyjones** [comment]
You can use other `--define` or [starlark build settings](https://bazel.build/extending/config#build-settings-and-select) for your `config_setting` instead.

**Comment by AttilaTheFun** [comment]
Ah okay! I'll give that a shot tomorrow. I think I can close this issue now, thanks!
