### ISSUE TITLE
New xctestrunner not passing environments to tests

### ISSUE THREAD

**Issue by andre-alves** [bazelbuild/rules_apple#1825]
Hi!

I'm using the new test runner from #1612  and noticed that I can't provide environments for tests.

I tried passing `--test_env` invocation and `env` dictionary, both didn't work:

```
.bazel test //BazelSample:DrinkDiscoveryTests --test_env MY_TEST=1
```

```
ios_unit_test(
    name = "DrinkDiscoveryTests",
    bundle_id = "br.com.test.DrinkDiscoveryTests",
    runner = "@build_bazel_rules_apple//apple/testing/default_runner:ios_xctestrun_ordered_runner",
    env = {
        "MY_TEST": "1"
    },
    minimum_os_version = "14.0"
)
```

The environment is not present inside tests:

```swift
let env = ProcessInfo.processInfo.environment["MY_TEST"] // nil
```

I also noticed that it's not providing the required environments from the [Test Encyclopedia](https://bazel.build/reference/test-encyclopedia) (I need `TEST_SRCDIR` for some evil things currently...).

I'm using Bazel 6.0, Xcode 14.1, and rules_apple from commit 2679f61b5f12b95baebe91f58ae695d8af328b05.

**Comment by tinder-cwybranowski** [comment]
I experienced the same thing, but resolved it by using `--test_env=CREATE_XCRESULT_BUNDLE=1` during the test execution.

[Cross-posting from my observation where I discovered the behavior](https://github.com/tinder-cwybranowski/bazel-swift-snapshot-testing/commit/4d516aa1765b1756652197d06fa40d40433a5f3d#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R15):
> Any values in 'ios_unit_test.env' / '--test_env' are only correctly propagated to the library test target at runtime when '--test_env=CREATE_XCRESULT_BUNDLE=1' is used. If that flag is not injected, then none of the env will be available to the implementation. Additionally, the flag must be injected via '--test_env', as it will not work by simply including it in the 'ios_unit_test.env'.

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_apple/pull/1826

**Comment by keith** [comment]
It was a bug in the codepath that uses simctl instead of xcodebuild to run the tests, CREATE_XCRESULT_BUNDLE forces the xcodebuild path, that PR should fix
