### ISSUE TITLE
How to implement a ios_unit_test_suite equivalent for ios_ui_test?

### ISSUE THREAD

**Issue by jverkoey** [bazelbuild/rules_apple#183]
We make use of [`ios_unit_test_suite` on the MDC iOS repo](https://github.com/material-components/material-components-ios/blob/develop/material_components_ios.bzl) in order to run unit tests against multiple simulator versions. We'd like to do the same with our UI tests, but there does not appear to be an equivalent for `ios_ui_test`. What is the recommend approach to making multiple runners for ui tests?

**Comment by sergiocampama** [comment]
we do have that, it can be loaded from apple/ios.bzl, we just hadn't documented it, [which we now have](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_ui_test_suite).
