### ISSUE TITLE
apple_static_xcframework: respect folder structure for headers

### ISSUE THREAD

**Issue by jagobagascon** [bazelbuild/rules_apple#1865]
Hi! I'm trying to create a static XCFramework that includes a bunch of third party C libraries. Some of these **libraries keep their headers in subfolders to avoid collisions with other libraries** and then add the subfolder in the import path.

Mbed-TLS for example expects its headers to be in the `mbedtls/` folder:
https://github.com/Mbed-TLS/mbedtls/blob/dd4427cc5baa068527fa4e10fc6a270876749f90/include/mbedtls/asn1.h#L27

**The problem is that** when I'm trying to create the XCFramework using the `apple_static_xcframework` rule, **all the headers are copied into the `Headers` folder, so when I try to import the framework into another project compilation fails** with errors like these:
```
2023-02-27T16:09:29.2679390Z /Users/runner/Library/Developer/Xcode/DerivedData/saltoapis-swift-hbgnfydppxbwficdfjezlngcuwit/Build/Products/Debug-iphonesimulator/SrpcNative.framework/Headers/aes.h:44:10: error: 'mbedtls/config.h' file not found
2023-02-27T16:09:29.2679870Z #include "mbedtls/config.h"
2023-02-27T16:09:29.2680070Z          ^
```

Is there any way of keeping the `mbedtls/` subfolder when creating an XCFramework?

**Comment by keith** [comment]
I think that instead of creating a xcframework that contains a framework bundle, you need one that contains a static library archive, and uses standard header path includes. Right now the apple_static_xcframework rule only supports the framework path, but you can test that setup by manually moving around the files to be a library instead.

**Comment by jagobagascon** [comment]
Can I do that using the `rules_apple` rules? Right now I'm adding a single `cc_library` as dependency for the xcframework:

```Bazel
cc_library(
    name = 'swift_c_bindings',
    srcs = glob(['**/*.c']),
    hdrs = public_headers + ['@mbedtls:headers'],
    deps = [...],
    tags = ["swift_module=%s" % native_module_name],
    visibility = [ "//visibility:public" ],
    alwayslink = True,
)

apple_static_xcframework(
    name = native_module_name,
    bundle_name = native_module_name,
    deps = [':swift_c_bindings'],
    ios = {
        "device": ["arm64"],
        "simulator": ["x86_64"],
    },
    minimum_os_versions = {
        "ios": "11.0"
    },
    public_hdrs = public_headers + ['@mbedtls:headers'],
)
```

**Comment by keith** [comment]
nope, that's what i mean with the manual stuff you can try as a test. alternatively you could swap the imports using `sed` or something in a genrule

**Comment by jagobagascon** [comment]
I ended up removing the Mbed-TLS headers from our framework. It required minor changes to our codebase, but since we already provide an abstraction layer for the library, we don't really need to make them public.

So I'm closing this issue, thanks for your help!
