### ISSUE TITLE
How to generate .dylib 

### ISSUE THREAD

**Issue by brappier** [bazelbuild/rules_apple#1869]
Is there any way to generate .dylib file from my code?

something like `swiftc -emit-library`

**Comment by brentleyjones** [comment]
There is `macos_dylib`, and https://github.com/bazelbuild/rules_apple/pull/987 would add `ios_dylib`.

**Comment by brappier** [comment]
Thanks,

How should i pass the swift file in that. what kind of dependency should it depend on?

**Comment by brentleyjones** [comment]
For https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-macos.md#macos_dylib, you would set it's `deps` to a `swift_library` from rules_swift.
