### ISSUE TITLE
[ios_xctestrun_runner] Allow simulator name input to test runner

### ISSUE THREAD

**Issue by mattrobmattrob** [bazelbuild/rules_apple#1873]
Allow simulator name to be passed into the `ios_xctestrun_runner` similar to how `device_id` would work for the old `ios_test_runner` via `--test_arg=--destination=platform=ios_simulator,id=$SIMULATOR_IDENTIFIER`:

https://github.com/bazelbuild/rules_apple/blob/e079b9bdc6a5218574fde349ed4525c6ed4359c7/apple/testing/default_runner/ios_test_runner.template.sh#L28-L34

`simulator_creator.py` already supports it:

https://github.com/bazelbuild/rules_apple/blob/e079b9bdc6a5218574fde349ed4525c6ed4359c7/apple/testing/default_runner/simulator_creator.py#L72-L74

This will allow persistent simulator usage across test bundles (similar to `REUSE_GLOBAL_SIMULATOR`) out of band from Bazel.

**Comment by keith** [comment]
sounds fine, just worth noting that if you change names it will affect test caching

**Comment by mattrobmattrob** [comment]
> sounds fine, just worth noting that if you change names it will affect test caching

Yup, in our case, we do it to mitigate simulator creation instability in the VMs on CI. And restart the VM in the case where it fails. Always using the same name on CI to get cache hits across the runs. Not perfect but it works for us.
