### ISSUE TITLE
[ios_xctestrun_runner] Allow no tests to be ran in a given test class

### ISSUE THREAD

**Issue by mattrobmattrob** [bazelbuild/rules_apple#1880]
If you use, for example, `test_filter` to avoid running a given test class function and it only has one function, it'll print the sentinel string that we use to determine nothing was ran.
```
Test Suite 'FooTests' started at 2023-03-02 18:24:41.560
Test Suite 'FooTests' passed at 2023-03-02 18:24:41.562.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.002) seconds
...
Test Suite 'FooTests.xctest' passed at 2023-03-02 18:24:42.279.
	 Executed 34 tests, with 0 failures (0 unexpected) in 42.874 (42.913) seconds
Test Suite 'Selected tests' passed at 2023-03-02 18:24:42.279.
	 Executed 34 tests, with 0 failures (0 unexpected) in 42.874 (42.914) seconds
```

Harden this check for this type of scenario:
https://github.com/bazelbuild/rules_apple/blob/f6ca3abf640adb3ecf3c32f0342aea91d7763ab5/apple/testing/default_runner/ios_xctestrun_runner.template.sh#L241-L244

Full XCTest log when nothing is ran:
```
2023-03-02 11:50:58.307 xctest[25112:9162009] warning: The 'BUILD_WORKSPACE_DIRECTORY' environment variable was not set. Test issue navigation might not work.
Test Suite 'All tests' started at 2023-03-02 11:50:58.343
Test Suite 'All tests' passed at 2023-03-02 11:50:58.344.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
2023-03-02 18:50:58.616 xcodebuild[25108:9161966] [MT] IDETestOperationsObserverDebug: 0.483 elapsed -- Testing started completed.
2023-03-02 18:50:58.616 xcodebuild[25108:9161966] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2023-03-02 18:50:58.616 xcodebuild[25108:9161966] [MT] IDETestOperationsObserverDebug: 0.483 sec, +0.483 sec -- end
```

**Comment by keith** [comment]
maybe we should just make this check not apply when a filter applies? pretty low risk i think

**Comment by keith** [comment]
yea im not really sure. i could see someone accidentally doing an incorrect filter and getting 0 as well, so maybe your current PR is better

**Comment by mattrobmattrob** [comment]
It is nice for a `bazel test //...` to apply exclusion of this check via `--test_filter` presence so those without `--test_filter` are still validated to actually run something vs. a global `bazel test --test_env=ALLOW_EMPTY_TEST_BUNDLE=1 //...` that hides it.

**Comment by mattrobmattrob** [comment]
I just swapped the PR to checking the `test_filter` so we can just assume you know what you're doing if you're intentionally filtering things. That works for us/accomplishes the goal of this issue, imo. 👍

**Comment by keith** [comment]
i actually meant when you had both a new var + test filter. but im not sure if it's worth the new var or not. my only worry with that path is that if you aren't passing `--test_output=all` you might not even see that nothing is run if you have an incorrect filter

**Comment by keith** [comment]
i wonder if any other rulesets handle this

**Comment by keith** [comment]
should be able to do that with another grep in that if statement
