### ISSUE TITLE
[ios_xctestrun_runner] test_filter not working for UI tests in Swift

### ISSUE THREAD

**Issue by mjburghard** [bazelbuild/rules_apple#1899]
PR https://github.com/bazelbuild/rules_apple/pull/1878 introduced support for test_filtering for the new ios_xctestrun_runner, but issues with `OnlyTestIdentifiers` were mentioned ( see https://github.com/bazelbuild/rules_apple/pull/1878#issuecomment-1452252778).
I investigated this a bit and think it is due to the missing `ProductModuleName` entry in the generated .xctestrun file.
Based on some of my testing, UI tests written in ObjC are not affected and still work.

Adding this entry manually to the xctestrun file fixes the issue as far as I can see. 
If somebody can give me a couple of hints how to get the correct value to forward to the template expansion, I can contribute a fix for this.

**Comment by keith** [comment]
@mattrobmattrob want to look at the fix? It sounds like we just need to pass around the attribute similar to https://github.com/google/xctestrunner/blob/24629f3e6c0dda397f14924b64eb45d04433c07e/xctestrunner/test_runner/xctestrun.py#L514
