### ISSUE TITLE
apple_static_framework_import is not defined

### ISSUE THREAD

**Issue by algasami** [bazelbuild/rules_apple#1934]
```
Xcode = 14.3
rules_apple = 2.2.0
```
The compiler failed at my `apple_static_framework_import` line, yielding that it is not defined. I've checked my `WORKSPACE` file to ensure that I'm in the latest version of `rules_apple 2.2.0`.
This is my `WORKSPACE` file.
```
MIN_IOS_VERSION = "16.0"
load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_application",
)
ios_application(
#Name of your application
    name = "-----",
#Bundle_id – should coincide with the one mentioned in the application
    bundle_id = "-----",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["Info.plist"],
    minimum_os_version = MIN_IOS_VERSION,
#Path to your provisioning_profile file
        provisioning_profile = "//mediapipe/examples/action_recognition:provisioning_profile.mobileprovision",
    deps = [":PoseTrackingGpuAppLibrary"],
)
objc_library(
    name = "PoseTrackingGpuAppLibrary",
    srcs = [
        "ViewController.mm",
    ],
    hdrs = [
        "ViewController.h",
    ],
    copts = ["-std=c++17"],
    data = [
        "//mediapipe/graphs/pose_tracking:pose_tracking_gpu.binarypb",
        "//mediapipe/modules/pose_detection:pose_detection.tflite",
        "//mediapipe/modules/pose_landmark:pose_landmark_full.tflite",
    ],
    sdk_frameworks = [
        "Metal",
    ],
    deps = [
        "//mediapipe/examples/ios/common:CommonMediaPipeAppLibrary",
        "//mediapipe/framework/formats:landmark_cc_proto",
        ":opencv"
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
        ],
    }),
)
apple_static_framework_import(
    name = "opencv",
    framework_imports = glob(["opencv2.framework/**"])
)
```
error messages:
```
BUILD:50:1: name 'apple_static_framework_import' is not defined
```

**Comment by keith** [comment]
Unless you're omitting something there you need to add a load statement to import it. See the docs for specifically where it comes from

**Comment by algasami** [comment]
I see. I also checked my rules_apple's version, which is `1.1.3`. I browsed through the [document](https://github.com/bazelbuild/rules_apple/blob/f8b14ce7516f9055861f91a9e5ff9d299c9d609f/doc/rules-apple.md#apple_dynamic_framework_import) of it, but it only said that `apple_static_framework_import` is a rule that applies to all Apple platform. Where could I find the correct path to load it?

**Comment by keith** [comment]
Ah your original description implies it was using a newer version, it might not have been added in that version, I don't recall.

**Comment by algasami** [comment]
Thanks for the info. I think I have to do more research into that particular version.
Btw, how do I import `apple_static_framework_import` in the newest(2.2.0) version? Is it included as a global rule, which is indicated by `rules-apple.md`?

**Comment by keith** [comment]
The only bazel rules that are global are some legacy ones that live in bazel itself (and they won't be global for long). So everything in rules_apple and any other third party ruleset requires an import.

You want:

```bzl
load("@build_bazel_rules_apple//apple:apple.bzl", "apple_static_framework_import")
```

**Comment by algasami** [comment]
Thanks. I really appreciate your help throughout this thread! I’ll close it for now since I’ve changed my method to the legacy one to fix this issue.
