### ISSUE TITLE
[ios_unit_test] Missing `_main` on latest update

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/rules_apple#195]
Running into this error on the latest `rules_apple` / `xctestrunner`  with `ios_unit_test`

```
Undefined symbols for architecture x86_64:   "_main", referenced from:      implicit entry/start for main executable
```
Is there an easy way to fix this?

**Comment by jerrymarino** [comment]
This is caused by changes in the `crosstool` in the latest Bazel and just needed to be correctly handled on my end. Thanks again for making such a great product 👍

**Comment by allevato** [comment]
If it's not too much trouble, would you mind pointing us at the CROSSTOOL change that caused the problem you ran into? We'd like to have a better way of tracking those changes.

**Comment by jerrymarino** [comment]
@allevato the issue I ran into was not with the `crosstool` _in Bazel_ per say: there are kinks in a custom workflow generating `CROSSTOOL`s and associated `BUILD` files.

Additionally: I've tested out the latest `rules_apple` and `0.15.0` in several contexts and is working perfect. The original reported issue occurred between the keyboard and chair.
