### ISSUE TITLE
Rules_apple fails on Bazel@HEAD in downstream CI.

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_apple#1956]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2997#0187e486-336b-4f41-9a92-f6c60a3ce01d

Platform :  rules_apple (Latest Bazel on :mac: (OpenJDK 11, Xcode))

Logs:
```
ERROR: /Users/buildkite/builds/bk-imacpro-17/bazel-downstream-projects/rules_apple/test/starlark_tests/rules/apple_verification_test.bzl:77:43: transition output '//command_line_option:apple_bitcode' does not correspond to a valid setting
--
  | (04:16:15) ERROR: /Users/buildkite/builds/bk-imacpro-17/bazel-downstream-projects/rules_apple/test/starlark_tests/BUILD:128:26: Errors encountered while applying Starlark transition
  | (04:16:15) ERROR: Analysis of target '//test/starlark_tests:tvos_unit_test_test_bundle_id_override' failed; build aborted:

```

[Culprit](https://github.com/bazelbuild/bazel/commit/37b8e1b37d5676b3d047b528149546bf2bfefdd1) :  https://buildkite.com/bazel/culprit-finder/builds/5478#0187e628-15b5-4551-a37f-4229dfbd5afb

Steps Followed:

1. git clone https://github.com/bazelbuild/rules_apple.git
2. git reset 796fae619b82a6b804af0735c16732fc0df8b943 --hard
3. export USE_BAZEL_VERSION=8087520b153832656695fef6f3654ed432642c98
4. bazel build tools/... test/...

CC @meteorcloudy

**Comment by sgowroji** [comment]
Seeing the same error on [rules_swift](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2997#0187e485-f325-4521-be63-5062ff26b5a2)

**Comment by meteorcloudy** [comment]
Probably caused by https://github.com/bazelbuild/bazel/commit/37b8e1b37d5676b3d047b528149546bf2bfefdd1, /cc @keith

**Comment by meteorcloudy** [comment]
Maybe https://github.com/bazel-contrib/bazel_features can help if you want to detect if this feature was removed or not.

**Comment by meteorcloudy** [comment]
FYI @lberki @oquenchil

**Comment by keith** [comment]
blocked on https://github.com/bazelbuild/bazel/issues/18321

**Comment by meteorcloudy** [comment]
After this is fixed, can you please also help address https://github.com/bazelbuild/examples/issues/288 ?

**Comment by keith** [comment]
https://github.com/bazelbuild/examples/pull/289
