### ISSUE TITLE
.strings files are not converted to binary

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#197]
Using the `objc_library` rule (or `objc_bundle_library`), strings files in either the `strings` or `resources` keys are not processed by `plutil` in order to convert them to binary plists.

Using the attached project you can see this behavior with:

```sh
bazel build //:App
unzip bazel-bin/App.ipa
file Payload/App.app/Localizable.strings
cat Payload/App.app/Localizable.strings
```

You'll see the Localizable.strings file is still the same as it was originally:

```
"Foo" = "bar";
```

[stringsfile.zip](https://github.com/bazelbuild/rules_apple/files/2204265/stringsfile.zip)

```
% bazel version
Build label: 0.15.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 26 12:42:27 2018 (1530016947)
Build timestamp: 1530016947
Build timestamp as int: 1530016947
```

**Comment by keith** [comment]
Possibly related to https://github.com/bazelbuild/rules_apple/issues/1

**Comment by allevato** [comment]
Are you using version [0.6.0](https://github.com/bazelbuild/rules_apple/releases/tag/0.6.0) of the rules? If so, this is working as intended; see the release notes:

> Only process plist and strings files for builds using `--compilation_mode=opt`.

We added this as a performance improvement when bundling during local development; when you build in `opt` mode (for release) the files will be converted to binary form.

**Comment by keith** [comment]
Ah thanks for the context! We had a different issue that led me to assume this was the problem, since I didn't know this case was supported.
