### ISSUE TITLE
can not use the path variables macro defined and "$SRCROOT/"

### ISSUE THREAD

**Issue by uiChuanqi** [bazelbuild/rules_apple#1985]
Hi,

I‘d like to try to write an script to , but when i try to use the path variables bazel defined in it, there coms out an error like this:

this is my script:
```
root_path="$SRCROOT/"
project_path="${BAZEL_WORKSPACE_ROOT}"
build_path="${TARGET_TEMP_DIR}"
mkdir -p "${root_path}/filterFiles"
mkdir -p "${project_path}/ios_test"
mkdir -p "${build_path}/gather_test"
```
#Error
```
mkdir: //filterFiles: Operation not permitted
mkdir: /ios_test: Operation not permitted
mkdir: /gather_test: Operation not permitted
```

 It seems that the "project_path" and "root_path" are both null, and i find this [xcodeproj/internal/templates/create_xcode_overlay.sh](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/4dff71b4838d4ac800fca58d8b7fd1b4410e0d92/xcodeproj/internal/templates/create_xcode_overlay.sh) has used it,  "TARGET_TEMP_DIR" has been defined by bazel in the project User-Defined:
<img width="985" alt="2023-06-08 22 30 15" src="https://github.com/bazelbuild/rules_apple/assets/112925246/cebd95ee-d53c-48da-9960-7564c5230469">

i don't know where the problem is, i am a new developer, could you give me some suggesstions about this ? Thank you!

**Comment by luispadron** [comment]
This seems like an issue for https://github.com/MobileNativeFoundation/rules_xcodeproj, I'd recommend posting in there.

Not entirely sure where your script is defined but typically you access the source tree path via: `BUILD_WORKSPACE_DIRECTORY`

**Comment by brentleyjones** [comment]
@keith Can you transfer this issue (I can't for some reason)?

**Comment by keith** [comment]
I can't either

**Comment by uiChuanqi** [comment]
> This seems like an issue for https://github.com/MobileNativeFoundation/rules_xcodeproj, I'd recommend posting in there.
> 
> Not entirely sure where your script is defined but typically you access the source tree path via: `BUILD_WORKSPACE_DIRECTORY`

hi, this is the screenshot of my project:
<img width="723" alt="2023-06-29 18 42 45" src="https://github.com/bazelbuild/rules_apple/assets/112925246/26e76b63-a0d6-4c45-a62c-5f1e4c4b0d79">

**Comment by brentleyjones** [comment]
Those variables are an internal implementation detail for the script. And that script is an implementation detail of the Xcode->Bazel integration.

In Xcode, `BUILD_WORKSPACE_DIRECTORY` is defined to be `SRCROOT`, so you can just use `SRCROOT` like normal. `PROJECT_DIR` is slightly different than normal, and is defined to be the Bazel execution root.

But based on your error, it seems you are running your script outside of Xcode, so all of that doesn't apply to you. `BUILD_WORKSPACE_DIRECTORY` is defined by Bazel (which is where your script seems to be?) to be the root of your workspace.

**Comment by uiChuanqi** [comment]
> Those variables are an internal implementation detail for the script. And that script is an implementation detail of the Xcode->Bazel integration.
> 
> In Xcode, `BUILD_WORKSPACE_DIRECTORY` is defined to be `SRCROOT`, so you can just use `SRCROOT` like normal. `PROJECT_DIR` is slightly different than normal, and is defined to be the Bazel execution root.
> 
> But based on your error, it seems you are running your script outside of Xcode, so all of that doesn't apply to you. `BUILD_WORKSPACE_DIRECTORY` is defined by Bazel (which is where your script seems to be?) to be the root of your workspace.

Got it ! Finally! Thank you very much for your explanation!

Yeah, you are right, i have been running  it outside of Xcode, it is written in my BUILD, because i want to create some files before the project generates:
```
sh_binary(
    name = "sb",
    srcs = ["Others/shtest.sh"],
    args = [
        "testFunc",
    ],
    visibility = ["//visibility:public"],
)
```
and this is my project screenshot:
<img width="723" alt="2023-06-29 18 42 45" src="https://github.com/bazelbuild/rules_apple/assets/112925246/ead57379-4607-433d-87b3-8a80a5fc2eb0">

when i run it in Xcode "Build Phases" by "Run Script" like below, it works very well: 
`sh "SampleApp/Others/shtest.sh"`

Thanks again for your explanation. Regards.
