### ISSUE TITLE
[ios_xctestrun_runner] Unable to force language or locale in tests

### ISSUE THREAD

**Issue by andre-alves** [bazelbuild/rules_apple#1996]
I'm trying to force some tests to run in a specific language/locale. In theory `xcodebuild` provide these args:

```
-testLanguage     constrains testing by specifying ISO 639-1 language in which to run the tests
-testRegion          constrains testing by specifying ISO 3166-1 region in which to run the tests
```

but they don't work for me, it's like `xcodebuild` ignores these arguments because nothing changes. The test still executes using the simulator's default setting.

```
ios_xctestrun_runner(
    name = "ios_standard_runner",
    create_xcresult_bundle = True,
    reuse_simulator = True,
    xcodebuild_args = ["-testLanguage", "en"],
)
```

Tried a lot of variations like ` ["-testLanguage", "(en)"]`, ` ["-testLanguage", "\"(en)\""]`,  `["\"-testLanguage (en)\""]`. I also tried modifying `ios_xctestrun_runner.template.sh` directly:

```
xcodebuild test-without-building -testLanguage "(en)" "${args[@]}" \
```

but couldn't get this to work at all.

Another approach that I tested and did work, is passing `-AppleLanguages` and `-AppleLocale` as `CommandLineArguments` in  xctestrun. What do you think about supporting `--command_line_args=-AppleLanguages,(en)` in the new runner?

`rules_xcodeproj` also supports `--command_line_args`  (https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/1520).

I can open the pull request with a diff similar to #1161.

**Comment by mattrobmattrob** [comment]
Have any sense for why adding it directly to `ios_xctestrun_runner.template.sh` didn't work? Does that mean the bundle/xctestrun itself can't be used with a different language?

**Comment by keith** [comment]
Maybe it has to be in the xctestrun file?

**Comment by andre-alves** [comment]
I will set up a small repro. So far the only way that works fine is by adding this key to the xctestrun file:

```
    <key>CommandLineArguments</key>
    <array>
        <string>-AppleLanguages (es)</string>
    </array>
```

Checking the result with:

```swift
    func test_preferredLanguage() {
        let lang = Locale.preferredLanguages.first!
        XCTAssertEqual(lang, "es")
    }
```

Passing `-testLanguage es` or `-testLanguage (es)` to xcodebuild didn't change the language.

Adding the key `TestLanguage` to the xctestrun file also didn't work:

```
    <key>TestLanguage</key>
    <string>es</string>
```

Tested with:
- Xcode 14.1
- ios_unit_test with host_app
- ios_unit_test without host_app

**Comment by mattrobmattrob** [comment]
I can help look after you have a simple repro. Thank you!

**Comment by andre-alves** [comment]
Thanks for all the help, really appreciate it.

The repro is here:
https://github.com/andre-alves/rules_apple_force_lang_repro

**Comment by mattrobmattrob** [comment]
We can close this now, right, @andre-alves?
