### ISSUE TITLE
[ios_xctestrun_runner] template conflict with `--xcodebuild_args=-parallel-testing-enabled`

### ISSUE THREAD

**Issue by iainsmith** [bazelbuild/rules_apple#2008]
[Slack discussion](https://bazelbuild.slack.com/archives/CD3QY5C2X/p1688465096308469)

The current implementation of `ios_xctestrun_runner.template.sh` assumes that it can find the "Executed {} tests" string, which isn't present when using parallel testing.

```bash
test_target_execution_count="$(grep -e "Executed [[:digit:]]\{1,\} tests*," "$testlog" | tail -n1)"
if echo "$test_target_execution_count" | grep -q -e "Executed 0 tests, with 0 failures"; then
  echo "error: no tests were executed, is the test bundle empty?" >&2
  exit 1
fi
```

Flags for reproducing
`--test_arg=--xcodebuild_args=-parallel-testing-worker-count --test_arg=--xcodebuild_args=1 --test_arg=--xcodebuild_args=-parallel-testing-enabled --test_arg=--xcodebuild_args=YES --test_env=DEBUG_XCTESTRUNNER=1`

**Comment by keith** [comment]
we can probably fix by adding `|| true` after the `tail`

**Comment by kapoorlakshya** [comment]
@iainsmith Were you able to find a workaround for this? If not then I'll submit a PR.

**Comment by mattrobmattrob** [comment]
> @iainsmith Were you able to find a workaround for this? If not then I'll submit a PR.

Please add a small test in `ios_xctestrun_runner_unit_test.sh` for this case, if you end up opening a PR, @kapoorlakshya 🙏
