### ISSUE TITLE
Wrong sign for embed framework

### ISSUE THREAD

**Issue by xinzhengzhang** [bazelbuild/rules_apple#209]
Apple rules using entitlements which defined in `ios_application` to sign all  nested frameworks.
It will cause fail when uploading to the appstore.

It seems that master brach is far away from the release tag 0.6.0 and the issue still exists...
So I created a [patch](https://github.com/bazelbuild/rules_apple/compare/0.6.0...Bilibili:bl-0.6.0-dev) for this issue based on 0.6.0

Error message:
`ERROR: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'xxxxx' for key 'application-identifier' in 'Payload/xxx.app/Frameworks/yyy/yy' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."`

**Comment by sergiocampama** [comment]
I believe this was fixed in #182
