### ISSUE TITLE
How to build for M1 Mac, from an Intel Mac machine? 

### ISSUE THREAD

**Issue by brappier** [bazelbuild/rules_apple#2147]
I am building a .dylib, using `macos_dylib`

**Comment by thii** [comment]
Pass `--macos_cpus=arm64`, or `--cpu=darwin_arm64` to your build.

**Comment by brappier** [comment]
and what about compiling for intel on m1?

**Comment by keith** [comment]
same idea but pass `x86_64` instead of `arm64`
