### ISSUE TITLE
tags defined in ios_application not effect for inner rules

### ISSUE THREAD

**Issue by xinzhengzhang** [bazelbuild/rules_apple#220]
I set tags = ["no-cache"] in `ios_application`
It still seems not work for inner rules.

![wechatworkscreenshot_d4a770d4-bf40-4fe5-89b5-27dfbeb14e2e](https://user-images.githubusercontent.com/1487445/44650749-10a63600-aa1a-11e8-9330-9e7965cc9ef2.png)

**Comment by sergiocampama** [comment]
This should not be required any more once we migrate from macros to rules.

**Comment by keith** [comment]
For this case it looks like these should already be not cached https://github.com/bazelbuild/rules_apple//blob/88b6b80d5e4331b56eeeef8d0eb49526e351b1c1/apple/internal/codesigning_support.bzl#L381-L383
