### ISSUE TITLE
Support custom substitutions in plists and entitlements files

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#226]
Currently in our app we have some custom settings that we use across code, and entitlements files. To do this we define custom build settings, and reference them from our plist, and entitlements files, and then read the plist value in code. It ends up looking something like this:

```
# foo.xcconfig
APP_GROUP_SUITE_NAME = some id
```

```
# foo.entitlements
<key>com.apple.security.application-groups</key>
<array>
  <string>$(APP_GROUP_SUITE_NAME)</string>
</array>
```

```
# info.plist
<key>AppGroupSuiteName</key>
<string>${APP_GROUP_SUITE_NAME}</string>
```

```
# foo.swift
let appGroupSuiteName = Bundle.main.infoDictionary?["LFTAppGroupSuiteName"] as! String
```

I'm wondering if there's a specific reason bazel doesn't support custom substitutions to support this use case, or if this is something we could add to some of the rules.

**Comment by thomasvl** [comment]
This has come up before, the complexity is always how go to about expressing it in the BUILD files.

Since you'd likely end up needing to use `select` statements to conditionally assign values, you can use those same `select` statements to provide different fragments of info.plist files and since the rules take a list of files, they will get merged.

Another thing we've seen people do is write a simple rule to wrap [expand_template](https://docs.bazel.build/versions/master/skylark/lib/actions.html#expand_template), and simply use that to do their subs and feed the result in to the other rules.

**Comment by keith** [comment]
> you can use those same select statements to provide different fragments of info.plist files and since the rules take a list of files, they will get merged.

It seems like the downside for us would be checking in many plists just for this use case. For us we have a 6 configurations with different values for ~6 different keys, things like default oauth config, etc, so we'd have to check in quite a few plists.

We also currently use variables like this for our versioning, but I guess there might be an alternative to that with a different method in bazel

**Comment by keith** [comment]
Using the change here https://github.com/bazelbuild/rules_apple/pull/230 I was able to implement a simple custom rule for this:

```python
def _replace_plist_variables(ctx):
    input_file = ctx.file.plist
    output_plist = ctx.outputs.out

    control = struct(
        output = output_plist.path,
        plists = [input_file.path],
        target = str(ctx.label),
        variable_substitutions = struct(**ctx.attr.replacements),
        allow_missing_variables = True,
    )

    control_file = ctx.actions.declare_file(
        "%s-control" % output_plist.basename,
        sibling = output_plist,
    )
    ctx.actions.write(
        output = control_file,
        content = control.to_json(),
    )

    apple_action(
        ctx,
        inputs = [input_file, control_file],
        outputs = [output_plist],
        executable = ctx.executable._plisttool,
        arguments = [control_file.path],
        mnemonic = "ReplacePlistVariables",
    )


process_plist_vars = rule(
    attrs = {
        "plist": attr.label(
            mandatory = True,
            allow_files = [".plist"],
            single_file = True,
        ),
        "replacements": attr.string_dict(allow_empty = False),
        "_plisttool": attr.label(
            cfg = "host",
            default = Label("@build_bazel_rules_apple//tools/plisttool"),
            executable = True,
        ),
    },
    outputs = {"out": "%{plist}-replaced.plist"},
    implementation = _replace_plist_variables,
)
```

**Comment by keith** [comment]
There are some problems with calling this since you can't nest select statements in dictionaries, but I'm still able to use this by the value of a select to a function that provides the expected values. For example:

```python
  replacements = select({
    "//:debug": variables_for_configuration("debug"),
```

```python
def variables_for_configuration(configuration):
    return {
        "APP_GROUP_SUITE_NAME": app_group_for_configuration(configuration),
```

```python
def app_group_for_configuration(configuration):
    if configuration in _ENTERPRISE_CONFIGURATIONS:
        return "one"

    return "another"
```

**Comment by thomasvl** [comment]
Why do you need a custom rule for this, why now use [expand_template](https://docs.bazel.build/versions/master/skylark/lib/actions.html#expand_template) like suggested?

**Comment by keith** [comment]
Yep you're right, thanks!

**Comment by keith** [comment]
For others who might be interested in this, using expand_template can look something like this:

```bzl
def _replace_apple_variables(ctx):
    ctx.actions.expand_template(
        template = ctx.file.src,
        output = ctx.outputs.out,
        substitutions = ctx.attr.replacements,
    )

process_plist_vars = rule(
    attrs = dict(
        src = attr.label(mandatory = True, allow_single_file = [".plist"]),
        replacements = attr.string_dict(allow_empty = False),
    ),
    outputs = {"out": "%{name}-replaced.plist"},
    implementation = _replace_apple_variables,
)

process_entitlements_vars = rule(
    attrs = dict(
        src = attr.label(mandatory = True, allow_single_file = [".entitlements"]),
        replacements = attr.string_dict(allow_empty = False),
    ),
    outputs = {"out": "%{name}-replaced.entitlements"},
    implementation = _replace_apple_variables,
)
```
