### ISSUE TITLE
Could not find or use auto-linked framework

### ISSUE THREAD

**Issue by maximality** [bazelbuild/rules_apple#2271]
Hey!

We have Firebase [xcframeworks](https://github.com/firebase/firebase-ios-sdk/releases/tag/10.15.0) added to our project through `apple_static_xcframework_import`.
For some reason after updating the rules to more recent version (https://github.com/bazelbuild/rules_apple/commit/7a2573377d1cc233a487b4ce6070f5077765bc6e) and Xcode to 15.0 I see warnings at linking step:

```
ld: warning: Could not find or use auto-linked framework 'nanopb'
ld: warning: Could not find or use auto-linked framework 'FirebaseABTesting'
ld: warning: Could not find or use auto-linked framework 'FirebaseInstallations'
ld: warning: Could not find or use auto-linked framework 'GoogleDataTransport'
ld: warning: Could not find or use auto-linked framework 'GoogleAppMeasurement'
ld: warning: Could not find or use auto-linked framework 'GoogleUtilities'
ld: warning: Could not find or use auto-linked framework 'FirebaseCore'
ld: warning: Could not find or use auto-linked framework 'FirebaseSessions'
ld: warning: Could not find or use auto-linked framework 'FBLPromises'
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes'
ld: warning: Could not find or use auto-linked framework 'FirebaseCoreExtension'
ld: warning: Could not find or use auto-linked framework 'Promises'
```

Here is the BUILD file that we use for Firebase (https://gist.github.com/maximality/292d4251c34e3cc67bcc69bd73f40d1b).
Before this update everything worked fine.
I am not sure if it's connected to this issue which we're facing also: https://github.com/bazelbuild/rules_apple/issues/2264

Can you please help me out?
Thanks!

**Comment by maximality** [comment]
Sorry, there was an error in my project BUILD file. It's all good now.

**Comment by vakhidbetrakhmadov** [comment]
@maximality , hi, i facing a similar issue, thought the root cause might be different, but nevertheless can please share what helped in your case, thanks toy.

**Comment by keith** [comment]
in the past this has been because you're targeting the wrong platform somehow, if you want to file a new issue with a repro case we can potentially help debug
