### ISSUE TITLE
After updating to version 3.0.0 project building/generating/testing not working

### ISSUE THREAD

**Issue by mikhailmulyar** [bazelbuild/rules_apple#2275]
After updating to rules_apple 3.0.0 Bazel throws same error for all files in project
```
ERROR: One of the output paths 'bazel-out/ios-sim_arm64-min13.0-applebin_ios-ios_sim_arm64-fastbuild-ST-730ce623e53b/bin/CustomerApp' (belonging to //:CustomerApp) and 'bazel-out/ios-sim_arm64-min13.0-applebin_ios-ios_sim_arm64-fastbuild-ST-730ce623e53b/bin/CustomerApp/Services/PermissionService/PermissionServiceInterface_objs/PermissionStatus.swift.ast' (belonging to //CustomerApp/Services/PermissionService:PermissionServiceInterface) is a prefix of the other. These actions cannot be simultaneously present; please rename one of the output files or build just one of them
```

**Comment by mattrobmattrob** [comment]
@mikhailmulyar, do you have an example that reproduces this issue?

**Comment by mikhailmulyar** [comment]
@mattrobmattrob here is an example project 
[BazelIssue.zip](https://github.com/bazelbuild/rules_apple/files/12843219/BazelIssue.zip)
running `bazelisk run //:xcodeproj` reproduces it

**Comment by mattrobmattrob** [comment]
> @mattrobmattrob here is an example project [BazelIssue.zip](https://github.com/bazelbuild/rules_apple/files/12845579/BazelIssue.zip) running `bazelisk run //:xcodeproj` reproduces it

What version of Bazel, @mikhailmulyar?

**Comment by mattrobmattrob** [comment]
Some of the `//:CustomerApp` target's output ends up being a prefix of all the targets defined in the `//CustomerApp/...` package(s). That's invalid.

To unbreak `basilisk run //:xcodeproj`, you could do this:
```diff
diff --git a/BUILD b/BUILD
index fffe7a9..f462391 100644
--- a/BUILD
+++ b/BUILD
@@ -141,7 +141,7 @@ infoplists = [
 ]

 ios_application(
-    name = "CustomerApp",
+    name = "CustomerApplication",
     bundle_id = "com.bundle.id",
     families = ["iphone"],
     infoplists = infoplists + [":AppNameInfoPlist"],
@@ -168,7 +168,7 @@ xcodeproj(
     tags = ["manual"],
     top_level_targets = [
         top_level_target(
-            ":CustomerApp",
+            ":CustomerApplication",
         ),
     ],
 )
```

**Comment by mikhailmulyar** [comment]
@mattrobmattrob Thanks, it works. Strange that it wasn't issue before, but it helps.
