### ISSUE TITLE
`xcarchive` rule produces invalid bundleinfo entry for `ApplicationPath`

### ISSUE THREAD

**Issue by maxwellE** [bazelbuild/rules_apple#2278]
When producing xcarchives via the `xcarchive` rule the resulting `*.xcarchive/Info.plist` contains the following entry

```
		<key>ApplicationPath</key>
		<string>Products/Applications/SomeApp.app</string>
```

Xcode expects the Products component naturally, so it can be updated to 

```
		<key>ApplicationPath</key>
		<string>Applications/SomeApp.app</string>
```

This should unblock processing of xcarchives by certain services

**Comment by luispadron** [comment]
To test this can we just open the .xcarchive in Xcode and see if that fails?
