### ISSUE TITLE
Swift code is never optimized

### ISSUE THREAD

**Issue by romeno-moreno** [bazelbuild/rules_apple#2315]
There is currently no way to create a build with Swift optimizations truly enabled. Parameters like `-c opt` are supposed to generate optimized code, but in terms of performance, the generated *.ipa file is the same as a debug build

**Comment by mattrobmattrob** [comment]
Can you explain in more detail what "the same as a debug build" means? Do you have an example/repro repository that we can take a look at?

**Comment by keith** [comment]
You can also view the swiftc invocations with `--swiftcopt=-v` and you should see either `-O` or `-Osize` in the case you're passing `-c opt` to bazel
