### ISSUE TITLE
an regression issue about linkmap in 3.1.1

### ISSUE THREAD

**Issue by tinder-kaijing** [bazelbuild/rules_apple#2339]
Likely there is a regression issue about linkmap in 3.1.1, simllar as the issue, https://github.com/bazelbuild/rules_apple/issues/2279

The limkmap directory did not get created for some reason in rules_apple 3.1.1. after rolling back to rules_apple 2.5.0, the linkmap directory gets created again.

**Comment by tinder-kaijing** [comment]
I think I find the root cause about Linkmap issue now.
The root cause is from rules_xcodeproj, for some reason, the lastest rules_xcodeprj 1.13.0 doesn’t include the latest rules_apple 3.1.1 (it is supposed to be), The make_archive.py is wrong from rules_xcodeproj 1.13.0, which miss Linkmap portion. When we force to have rules_apple 3.1.1 before rules_xcodeprj 1.13.0 in WORKSPACE. the LInkmap files and directory were generated. Cc @brentleyjones be aware of this issue.

**Comment by brentleyjones** [comment]
Are you using Bzlmod or WORKSPACE? For Bzlmod rules_xcodeproj depends on the minimal version we support, to allow the greatest version compatibility. For WORKSPACE we generally try to depend on the latest, but sometimes we lag.

**Comment by tinder-kaijing** [comment]
> Are you using Bzlmod or WORKSPACE? For Bzlmod rules_xcodeproj depends on the minimal version we support, to allow the greatest version compatibility. For WORKSPACE we generally try to depend on the latest, but sometimes we lag.

@brentleyjones Thanks for looking at the issue. At this moment, we still use WORKSPACE, but in the process of moving to bzlmod :-)

**Comment by brentleyjones** [comment]
To follow Bzlmod logic then: if you use rules_apple directly (which you do), you should declare a dependency on it yourself before rules_xcodeproj declares the backup one.

**Comment by tinder-kaijing** [comment]
> To follow Bzlmod logic then: if you use rules_apple directly (which you do), you should declare a dependency on it yourself before rules_xcodeproj declares the backup one.
> 
> Or open a PR to rules_xcodeproj for us to update our macro 😊.

Got it. Thanks very much. Wii do 👍
