### ISSUE TITLE
dynamic frameworks won't strip archs since version 3.0.0

### ISSUE THREAD

**Issue by xiemotongye** [bazelbuild/rules_apple#2392]
We use bazel to organize & build our iOS application. All worked fine in version 2.5.0.

After I update bazel to version 7.0 & rules_apple to 3.2.1, I was surprised to find out that dynamic frameworks won't strip archs anymore when I upload ipa to AppStoreConnect. The dynamic frameworks in final payload still includes the simulator arch.

```
ERROR ITMS-90087: Unsupported Architectures. The executable for MyApp.app/Frameworks/MyFmk.framework contains unsupported architectures '[x86_64]'.
```

I've confirmed that this issue has been around since version 3.0.0.

**Comment by xiemotongye** [comment]
I've send a PR to fix this. https://github.com/bazelbuild/rules_apple/pull/2395
This issue may block the release plan of some iOS-dev teams that want to use bazel 7.
@keith Can you have a look?

**Comment by keith** [comment]
thanks for debugging this! I submitted a PR similar to yours to fix what you found and cover that with a test https://github.com/bazelbuild/rules_apple/pull/2398
