### ISSUE TITLE
Mixed Objective-C and Swift library

### ISSUE THREAD

**Issue by marciniwanicki** [bazelbuild/rules_apple#240]
I've seen the introp example https://github.com/bazelbuild/rules_swift/tree/master/examples/apple/objc_interop, I wonder if there is any way to build a single library with both Swift and Objective-C classes seeing each other.

**Comment by keith** [comment]
@ob

**Comment by ob** [comment]
I started working on this (there's even a [design document](https://docs.google.com/document/d/1v9DeNdPbQoGdemvH2hC3l2YSgk57uDkSzA7pwHNCbEM/edit?usp=sharing)), but got distracted.

**Comment by ob** [comment]
Sorry, no updates yet... still stalled with other stuff :-(

**Comment by ajanuar** [comment]
any update?

**Comment by LeeWong** [comment]
any update?

**Comment by ob** [comment]
Realistically, I don't think this is going to happen until the `cc_rules` are pulled out of the bazel main repo.

**Comment by LeeWong** [comment]
@ob , do you know if there is any plan to pull out cc_rules? When it might happen? Thanks.

**Comment by acecilia** [comment]
Buck already supports this, as far as I read: https://buck.build/rule/apple_library.html

**Comment by thii** [comment]
There’s a way to work around this, is to build a fat static framework for third-party distribution, then import it using `apple_static_framework_inport`.

**Comment by edias** [comment]
Does anybody have an update or example with mixed Objective-C/Swift with a single rule?

**Comment by ob** [comment]
@edias we are working on https://github.com/ob/rules_ios but it's pretty early on.

**Comment by leohahn** [comment]
Do we have any updates on this?

**Comment by acecilia** [comment]
@leohahn yes. Please see https://github.com/bazel-ios/rules_ios/blob/master/docs/framework_doc.md
