### ISSUE TITLE
Generated IPA rejected by App Store when Swift dependency present

### ISSUE THREAD

**Issue by jdelfino** [bazelbuild/rules_apple#241]
We're building an IPA with the `ios_application` rule, and getting the following response after trying to upload it to TestFlight:

```
Invalid Swift Support - The files libswiftCoreGraphics.dylib, libswiftDarwin.dylib, libswiftCoreAudio.dylib, libswiftos.dylib, libswiftQuartzCore.dylib, libswiftFoundation.dylib, libswiftMetal.dylib, libswiftCoreFoundation.dylib, libswiftCoreImage.dylib, libswiftObjectiveC.dylib, libswiftUIKit.dylib, libswiftDispatch.dylib, libswiftCore.dylib 
don’t match
/Payload/Canopy.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/Canopy.app/Frameworks/libswiftDarwin.dylib, /Payload/Canopy.app/Frameworks/libswiftCoreAudio.dylib, /Payload/Canopy.app/Frameworks/libswiftos.dylib, /Payload/Canopy.app/Frameworks/libswiftQuartzCore.dylib, /Payload/Canopy.app/Frameworks/libswiftFoundation.dylib, /Payload/Canopy.app/Frameworks/libswiftMetal.dylib, /Payload/Canopy.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/Canopy.app/Frameworks/libswiftCoreImage.dylib, /Payload/Canopy.app/Frameworks/libswiftObjectiveC.dylib, /Payload/Canopy.app/Frameworks/libswiftUIKit.dylib, /Payload/Canopy.app/Frameworks/libswiftDispatch.dylib, /Payload/Canopy.app/Frameworks/libswiftCore.dylib. 
Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to 
/Payload/Canopy.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/Canopy.app/Frameworks/libswiftDarwin.dylib, /Payload/Canopy.app/Frameworks/libswiftCoreAudio.dylib, /Payload/Canopy.app/Frameworks/libswiftos.dylib, /Payload/Canopy.app/Frameworks/libswiftQuartzCore.dylib, /Payload/Canopy.app/Frameworks/libswiftFoundation.dylib, /Payload/Canopy.app/Frameworks/libswiftMetal.dylib, /Payload/Canopy.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/Canopy.app/Frameworks/libswiftCoreImage.dylib, /Payload/Canopy.app/Frameworks/libswiftObjectiveC.dylib, /Payload/Canopy.app/Frameworks/libswiftUIKit.dylib, /Payload/Canopy.app/Frameworks/libswiftDispatch.dylib, /Payload/Canopy.app/Frameworks/libswiftCore.dylib.
```

Importantly, this error just started yesterday - we released successfully earlier this week. We've even re-built the previously-successful release from its tag, and tried to release it again with a newer build number, and that failed. So, we think something has changed on the App Store side to start rejecting these files, as opposed to code changes, XCode changes, or Bazel rule changes. We've tried with both tip of master `rules_apple` and tag `0.8.0`.

My original suspicion was that this had to do with the fact that Payload/<app>/Frameworks/* is getting signed ([code](https://github.com/bazelbuild/rules_apple/blob/658dd7b5423ee35a134784b31bea05f7a1b37030/apple/internal/codesigning_actions.bzl#L83)). However, I manually unzipped the generated IPA, copied `SwiftSupport/iphoneos/*` to `Payload/<app>/Frameworks/`, re-signed, and tried to upload, and it still failed with the same message, so I wonder if all of those files are being modified somehow earlier in the build process.

Any ideas about what's going on, where to look further, or workarounds? Thanks!

**Comment by sergiocampama** [comment]
If you take a the build that was successful, and the one that failed, and compare the dylibs with a checksum, are they different? Did you change the version of Xcode between the successful and the failure cases? I'm wondering if newer Xcodes are doing something different with the dylibs.

**Comment by jdelfino** [comment]
The build from XCode 10.0 worked, so that seems to confirm that the problem is in the 10.0->10.1 upgrade.

**Comment by sergiocampama** [comment]
Thanks for confirming. I'll take a look to see if there's anything Xcode 10.1 is doing differently with regards to the SwiftSupport files.
