### ISSUE TITLE
Bazel 7: Linking actions missing`-framework` flags for framework imports

### ISSUE THREAD

**Issue by chiragramani** [bazelbuild/rules_apple#2427]
Repro:
`bazel aquery //examples/ios/HelloWorldSwift:UnitTests.__internal__.__test_bundle`
[rules_apple-master 2.zip](https://github.com/bazelbuild/rules_apple/files/14547827/rules_apple-master.2.zip)

```
-Fexamples/ios/HelloWorldSwift/ExampleFramework.xcframework/ios-arm64_x86_64-simulator \
-framework \
Lottie \
```
is present when building with Bazel 6.x.x but not present with Bazel 7.x.x(tested on Bazel 7.1.0rc2).

The builds are successfully finishing, but I'm uncertain whether this is the anticipated behavior. Could any adjustments be required, considering this might be linked to https://github.com/bazelbuild/bazel/issues/19000?

[bazel6aquery.txt](https://github.com/bazelbuild/rules_apple/files/14547833/bazel6aquery.txt)
[bazel7aquery.txt](https://github.com/bazelbuild/rules_apple/files/14547834/bazel7aquery.txt)

**Comment by brentleyjones** [comment]
This is expected as part of the migration away from `ObjCProvider`. The executables of frameworks are listed directly in the linkopts now (you might notice they use the mangled form as well).

**Comment by chiragramani** [comment]
This makes sense. Appreciate you looking into it @brentleyjones. I am closing this as it's not an issue.
