### ISSUE TITLE
Bazel CI: rules_apple is failing after upgrading Mac machines to Xcode 10.1 and macOS 10.14.1

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_apple#243]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/577#e1a08dc7-0b3e-429c-b9d3-90219ad500ac

@sergiocampama Can you help taking a look and make rules_apple work with the latest Xcode?

**Comment by meteorcloudy** [comment]
@sergiocampama Thanks for the fix, but we still have one more test failing
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/583#bcdeb297-941e-4886-ae4c-c9f665df7563
```
ERROR: /private/var/tmp/_bazel_buildkite/c3f91de9840a88e566556e19ce7285a9/execroot/build_bazel_rules_apple/_tmp/70c3ba88937a680dfcd869bde070468a/workspace/app/BUILD:22:1: AssetCatalogCompile app/ext.resources/actool-output failed (Exit 255): xctoolrunner failed: error executing command 
  (cd /private/var/tmp/_bazel_buildkite/c3f91de9840a88e566556e19ce7285a9/execroot/build_bazel_rules_apple/_tmp/70c3ba88937a680dfcd869bde070468a/_bazel_buildkite/cce69e97264aabbc96b3698bea9832a7/execroot/build_bazel_rules_apple_integration_tests && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=12.1 \
    XCODE_VERSION_OVERRIDE=10.1.0 \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner actool --compile '[ABSOLUTE]bazel-out/darwin-opt/bin/app/ext.resources/actool-output' --platform iphoneos --output-partial-info-plist '[ABSOLUTE]bazel-out/darwin-opt/bin/app/ext.resources/actool-PartialInfo.plist' --minimum-deployment-target 10.0 --compress-pngs --product-type com.apple.product-type.app-extension.messages-sticker-pack --sticker-pack-identifier-prefix my.bundle.id.extension.sticker-pack. --app-icon app_icon --target-device iphone '[ABSOLUTE]external/build_bazel_rules_apple/test/testdata/resources/sticker_pack_ios.xcstickers')
Target //app:app failed to build
```

Please take a look

**Comment by sergiocampama** [comment]
That one is a flake we can't really control, as it's coming from one of the Xcode tools. Are all the tests running on the same mac? It could be a race condition of running all the tests at the same time. Wasn't there a way to mark a test as exclusive?

**Comment by meteorcloudy** [comment]
Yes, you have to add `tags = ["exclusive"]` for that test.
Search "exclusive" in "https://docs.bazel.build/versions/master/be/common-definitions.html

**Comment by thomasvl** [comment]
The default is to not shard things, so I thought at one point things were already down to one at a time, but maybe that was more luck in bazel scheduling, it likely is something to validate on the integration tests in general.
