### ISSUE TITLE
ios_application with launch xcassets containing pdf images

### ISSUE THREAD

**Issue by vakhidbetrakhmadov** [bazelbuild/rules_apple#2507]
Hi,

How do i set up launch xcassets with [ios_application](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application) ?

When trying
```
ios_application(
...,
launch_images = glob([Launch.xcassets/**]),
)
```
i get the following error
```
Error in fail: Expected the xcassets directory to only contain files are in sub-directories with the extension launchimage, but found the following: [
  Launch.xcassets/splash.imageset/Contents.json,
  Launch.xcassets/splash.imageset/light.pdf,
  Launch.xcassets/splash.imageset/dark.pdf
```

And if i change the extension of splash.imageset to launchimage i get
```
error: The launch image set "splash" references a file "light.pdf", but that file does not have a valid extension.
error: The launch image set "splash" references a file "dark.pdf", but that file does not have a valid extension.
error: The launch image set "splash" has 2 unassigned children.
```

**Comment by mattrobmattrob** [comment]
Can you test that it works with a PNG image in your structure?

**Comment by vakhidbetrakhmadov** [comment]
Updated `Launch.xcassets` like so 
```
$ ls -1 Launch.xcassets
Contents.json
splash.imageset

$ cat Launch.xcassets/Contents.json
{
  "info" : {
    "version" : 1,
    "author" : "xcode"
  }
}

$ ls -1 Launch.xcassets/splash.imageset
Contents.json
logo.png

$ cat Launch.xcassets/splash.imageset/Contents.json
{
  "images" : [
    {
      "idiom" : "universal",
      "filename" : "logo.png"
    }
  ],
  "info" : {
    "version" : 1,
    "author" : "xcode"
  }
}
```

And still getting 

```
error: The launch image set "logo" has an unassigned child.
```

**Comment by mattrobmattrob** [comment]
FWIW, launch images of this format work for me: https://github.com/mattrobmattrob/bazel-ios-swiftui-template/commit/95558bafccac320bb5186ffe21d0b33b67a8848c

**Comment by vakhidbetrakhmadov** [comment]
Thank you very much! 

Sorry, i actually confused `launch_images` and thought it's designed for specifically providing assets to `launch_storyboard`, but those should just go into `resources`.

I now understand that `launch_images` is for providing static images displayed on app launch.

The issue can be closed 🙏
