### ISSUE TITLE
Update needed to apple_support.run() to support corresponding change in rules_apple 1.17.1

### ISSUE THREAD

**Issue by francine-blanc** [bazelbuild/rules_apple#2557]
The `_run()` function in `build_bazel_apple_support/lib/apple_support.bzl`  has been updated [here  in version 1.17.1](https://github.com/bazelbuild/apple_support/commit/0fddd9c495cf8e7927640ca080d84b515fe12c2e#diff-8da4c3cdbc3afa122c0237931cb6a8db95a2b10ce7d77ab56ab0c33bcfc5aa69L316)  so that only keyword arguments, and not positional arguments, are acceptable.

the `apple_support.run()` function in `build_bazel_rules_apple/apple.dtrace.bzl` however still expects `ctx`  as a positional argument, seen [here](https://github.com/bazelbuild/rules_apple/blob/b4a1d1e71ee655ff6d6b51b5845757377febf321/apple/dtrace.bzl#L46).

Now with the above change, this function no longer works as intended, leading to errors such as the following:
```
ERROR: /example/project/subfolder/BUILD.bazel:50:50: in dtrace_compile rule //project/subfolder:some_target 
     Traceback (most recent call last):
     	File "/..../external/build_bazel_rules_apple/apple/dtrace.bzl", line 50, column 26, in _dtrace_compile_impl
     		apple_support.run(
     	File "/..../external/build_bazel_apple_support/lib/apple_support.bzl", line 282, column 5, in _run
     		def _run(
     Error: _run() does not accept positional arguments, but got 1
```

So, it looks like `rules_apple` needs to be updated to support the change in the most recent version of the `apple_support` repo.

**Comment by xiemotongye** [comment]
I have the same issue. Downgrade `apple_support` to 1.15.1 can fix is error. Looks like `rules_apple` needs to be updated.
