### ISSUE TITLE
`mixed_language_library` data attribute ignored ?

### ISSUE THREAD

**Issue by vakhidbetrakhmadov** [bazelbuild/rules_apple#2573]
Hi,

I have the following setup: `ios_application` -> `mixed_language_library` -> `...`.

When i add a resource to `data` attribute of  the `mixed_language_library` i expect that resource to be included at the top level of the produced app bundle, currently that doesn't happen. 

Previously i had the following setup `ios_application` -> `apple_framework` -> `...` and it worked as expected.

**Comment by vakhidbetrakhmadov** [comment]
My current workaround is to use `resources` attribute of the `ios_application`

**Comment by vakhidbetrakhmadov** [comment]
Sorry, i confused the repository, should have opened this in `rules_swift`

**Comment by vakhidbetrakhmadov** [comment]
Reopened in `rules_swift`: https://github.com/bazelbuild/rules_swift/issues/1449

**Comment by brentleyjones** [comment]
Fixed by #2575.
