### ISSUE TITLE
[apple/testing/apple_test_rules.bzl] "env" value not passed to hosted ios_unit_test NSProcessInfo

### ISSUE THREAD

**Issue by romoore** [bazelbuild/rules_apple#304]
## Summary
The `env` values of `ios_unit_test` are not passed to `NSProcessInfo.processInfo.environment` in hosted unit tests (non-logic tests that have a custom `test_host` property set).  Using `--test_env` works as expected.

## Context/Detail

I'm trying to integrate https://github.com/material-foundation/ios-snapshot-test-case as a snapshot testing framework into our test targets.

I've attempted to [define the "env" variable "FB_REFERENCE_IMAGE_DIR" in a skylark rule for snapshot tests](https://github.com/material-components/material-components-ios/blob/f5c92fd1378d1410cb074e4a46ffdd51d8afcc95/material_components_ios.bzl#L186) (we'll be creating several dozen of these). 

```
def mdc_snapshot_test(
    name,
    deps = [],
    minimum_os_version = SNAPSHOT_IOS_MINIMUM_OS,
    visibility = ["//visibility:private"],
    size = "medium",
    **kwargs):
    
  test = "%sTest" % name
  app = "%sApp" % name

  """Declare an MDC ios_unit_test for snapshot tests."""
  ios_unit_test(
      name = test,
      deps = ["//components/private/Snapshot/TestHost"] + deps,
      minimum_os_version = minimum_os_version,
      runner = SNAPSHOT_IOS_RUNNER_TARGET,
      test_host = ":%s" % app,
      visibility = visibility,
      env = {
          "FB_REFERENCE_IMAGE_DIR":"snapshot_test_goldens/goldens",
      },
      size = size,
      **kwargs)
```

When I inspect the environment runtime in the code under test using `[NSProcessInfo processInfo].environment`, I don't see the variable available.  When I pass `--test_env="FB_REFERENCE_IMAGE_DIR=$snapshot_dir"`, I see the value in the environment values and my code behaves as expected.  

Am I doing something wrong, or [am I misreading the documentation for this variable](https://github.com/bazelbuild/rules_apple/blob/24abca60f5ec59c5336b62a61714234c23a8d17c/doc/rules-ios.md)?

**Comment by keith** [comment]
This should be fixed by https://github.com/bazelbuild/rules_apple/pull/335 if you have a chance please try it and let me know if it fixes your use case!

**Comment by romoore** [comment]
If you believe this fixes the issue, we can close this as resolved for now. Since we rely on the `stable` branch of the rules (and might require other changes to upgrade), I'll have to adopt the new rules a bit more slowly in our project before I can confirm.  I will reopen or refile if it's still a problem. Thanks!
