### ISSUE TITLE
Test host with fonts

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#320]
Currently if you have a project with this dependency structure:

```
FooTests (ios_unit_test) -> Foo (swift_library) -> Foo["data"] = *.otf
FooTests["test_host"] = TestHost
```

When you run your tests, the fonts will exist in `FooTests` bundle, and not in `TestHost`'s. This causes an issue if your code validates that they're configured correctly.

A quick workaround is to add the fonts to the `data` of TestHost as well, but ideally this wouldn't be required.

**Comment by sergiocampama** [comment]
From the dependency graph point of view, the TestHost has no concept of the font being there. What kind of validation are you doing on the fonts themselves?

**Comment by keith** [comment]
Some of the tests happen to hit codepaths that validate the existence of the fonts. This isn't ideal but it was a bit surprising. I'll close this assuming the `data` workaround is the right solution
