### ISSUE TITLE
Strip symbols and bitcode from Swift standard libraries when building without bitcode

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#327]
Currently since rules_apple is [incompatible with bitcode](https://github.com/bazelbuild/rules_apple/issues/163), we should mirror Xcode's behavior which is to strip the dylibs of bitcode and symbols to reduce their size. I'm not entirely sure how this affects final download size, but the "strip swift symbols" checkbox when archive from Xcode does this.

More specifically Xcode invokes `ipatool` with this value, which happens to be a ruby script in Xcode. Here's the relevant logic:

```ruby
# What we do next depends on whether or not the Mach-O has bitcode.
if shouldCompileBitcode
  # Because we have to compile Mach-Os in dependency order, we defer the actual compilation.
  puts "  #{"|  " * level}.#{machoImage.arch} (compile)" if options.verbosity >= 2
  machoImagesToCompile << machoImage
elsif machoImage.shouldStripBitcode(options)
  # But we can strip bitcode from the binary right away (no need to defer).  We do so in-place.
  puts "  #{"|  " * level}.#{machoImage.arch} (strip)" if options.verbosity >= 2
  CmdSpec.new(locate_tool("bitcode_strip", [machoImage.platform.toolsPath]), [ "-r", "-o", machoImageOutputPath, machoImageInputPath ]).run(level)
  # Strip Swift symbols from Swift dylibs
  if machoImage.machoFile.isSwiftRuntimeDylib && ipa.stripSwiftSymbols
    CmdSpec.new(locate_tool("strip", [machoImage.platform.toolsPath]), [ "-ST", machoImageOutputPath ]).run(level)
  end
else
  # Otherwise, the Mach-O image doesn't have bitcode, so we strip swift symbols.

  # Strip Swift symbols from Swift dylibs
  if machoImage.machoFile.isSwiftRuntimeDylib && ipa.stripSwiftSymbols
    CmdSpec.new(locate_tool("strip", [machoImage.platform.toolsPath]), [ "-ST", "-o", machoImageOutputPath, "-", machoImageInputPath ]).run(level)
    verb = "strip-swift-dylib"
  else
    FileUtils.cp(machoImageInputPath, machoImageOutputPath)
    verb = "copy"
  end

  puts "  #{"|  " * level}.#{machoImage.arch} (#{verb})" if options.verbosity >= 2
end
```

Mainly the logic here is:

- If you're building with bitcode, do nothing, the future bitcode compilation will handle this
- Check if the binary has bitcode, if so, strip it out, if it is a swift dylib, strip the swift symbols as well (this is what the checkbox controls)
- If there's no bitcode, still strip the swift symbols from the dylib

**Comment by keith** [comment]
For our project for a single architecture (arm64) this has a massive impact on ipa size:

Before:

```
% du -sh Lyft.ipa
108M    Lyft.ipa
% du -sh SwiftSupport
41M     SwiftSupport
```

After:

```
% du -sh Lyft.ipa
81M     Lyft.ipa
% du -sh SwiftSupport
7.8M    SwiftSupport
```

**Comment by keith** [comment]
I assume this won't end up impacting app store builds since I assume apple will re-package those no matter what, but this would affect enterprise builds

**Comment by sergiocampama** [comment]
We might be able to do something inside the `swift_stdlib_tool.sh` tool, maybe pass an argument to do the stripping of the bitcode support.

**Comment by brentleyjones** [comment]
We've recently run into this as well. It would be really nice if `rules_swift` stripped the Swift Symbols.

**Comment by brentleyjones** [comment]
To be clear, it should be more than `swift_stdlib_tool.sh`, since that would only strip the dylibs. We should also strip dynamic frameworks.

For example, HTMLEntities is a dynamic framework we use and it's 300kb when copied/stripped by Xcode but 1.4mb when handled by Bazel.

**Comment by brentleyjones** [comment]
We are now naively doing this with a `ipa_post_processor`:

```bash
#!/bin/bash

set -eo pipefail

readonly work_dir="$1"

# Strip SwiftSupport
if [ -d "$work_dir/SwiftSupport/" ]; then
    find "$work_dir/SwiftSupport/" -type f -name "*.dylib" -exec sh -c 'xcrun bitcode_strip -r -o {} {}' \;
    find "$work_dir/SwiftSupport/" -type f -name "*.dylib" -exec sh -c 'strip -ST {}' \;
fi

# Strip frameworks
find "$work_dir/Payload/" -type f -name "*.dylib" -exec sh -c 'xcrun bitcode_strip -r -o {} {}' \;
find "$work_dir/Payload/" -type f -name "*.dylib" -exec sh -c 'strip -ST {}' \;
find "$work_dir/Payload/" -type d -name "*.framework" -exec sh -c 'xcrun bitcode_strip -r -o {}/$(basename {} .framework) {}/$(basename {} .framework)' \;
find "$work_dir/Payload/" -type d -name "*.framework" -exec sh -c 'strip -ST {}/$(basename {} .framework)' \;
```

**Comment by brentleyjones** [comment]
We are now naively doing this with a `ipa_post_processor`:

```bash
#!/bin/bash

set -eo pipefail

readonly work_dir="$1"

# Strip  swiftlibs
find "$work_dir/Payload/" -type f -name "*.dylib" -exec sh -c 'xcrun bitcode_strip -r -o {} {}' \;

# Strip Frameworks
find "$work_dir/Payload/" -type d -name "*.framework" -exec sh -c 'xcrun bitcode_strip -r -o {}/$(basename {} .framework) {}/$(basename {} .framework)' \;
find "$work_dir/Payload/" -type d -name "*.framework" -exec sh -c 'xcrun strip -ST {}/$(basename {} .framework)' \;
```

The end result of this is a smaller IPA, but had no effect on reported sizes in the App Store.

**Comment by brentleyjones** [comment]
@thii I think #881 only strips bitcode, correct? What about the swift symbols? In my above example I call

```bash
find "$work_dir/Payload/" -type d -name "*.framework" -exec sh -c 'xcrun strip -ST {}/$(basename {} .framework)' \;
```

to strip Swift Symbols from imported frameworks.

**Comment by thii** [comment]
I totally forgot about it. `rules_apple` doesn't currently have something equivalent to Xcode's "strip swift symbols" checkbox. How does adding a new define for it sound? (stripping bitcode doesn't mean also to strip symbols, right?)

**Comment by brentleyjones** [comment]
A new flag sounds good. I like your approach in #979.

**Comment by keith** [comment]
Do we need a flag or could it be safe to opt everyone into this?

**Comment by brentleyjones** [comment]
Xcode has a checkbox, so I would prefer to give the same option?

**Comment by keith** [comment]
I think in general I would prefer that we don't add options until they have a solid use case. Also that reduces the shear number of options people have to know about, and reduces the diff from `upstream`. So in general if we can do the "right" thing for everyone I would prefer that until it's no longer the case.
