### ISSUE TITLE
Add bundles, resources, structured_resources to swift_library.

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#34]
`swift_library` should be able to propagate resources and bundles to applications/extensions/frameworks just like `objc_library` can.

This was almost working but had some weird issues with certain dependency graphs where the aspect wasn't drilling down into other deps for unknown reasons. Gotta investigate.

**Comment by allevato** [comment]
`resources` and `structured_resources` are now supported. (Things like `datamodels`, `storyboards`, `xibs`, etc. should just be placed in `resources` now.)

`bundles` will be coming soon.

**Comment by sergiocampama** [comment]
Obsolete. The current plan is to use `apple_bundle_import`, `apple_resource_bundle` and `apple_resource_group`, plus direct file references, through the `data` attribute.
