### ISSUE TITLE
incompatible_depset_is_not_iterable

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_apple#403]
Tests are broken when Bazel is run with `--incompatible_depset_is_not_iterable`, see: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/88#595c679c-0bbd-449c-9c5f-46b6dd2dd8a2

```
File "/private/var/tmp/_bazel_buildkite/7f093321fb3d2d9228bcf4e3d1fac902/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 351, in static_framework_names.append
--
  | depset([objc_provider_framework_name(fd...])
  | File "/private/var/tmp/_bazel_buildkite/7f093321fb3d2d9228bcf4e3d1fac902/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 352, in depset
  | [objc_provider_framework_name(fdir) for fdir in objc.framework_dir]
  | type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

Can you take a look?

**Comment by thomasvl** [comment]
So that failure is actually in rules_swift (note the path, we just depend on them).  But I believe that is already fixed in https://github.com/bazelbuild/rules_swift/pull/183, but rules_swift hasn't cut a release with the fix yet so we can update our deps.

@allevato @sergiocampama fyi
