### ISSUE TITLE
Case insensitive headers in `ios_static_framework`s

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#408]
When building a `ios_static_framework` for the [`CgRPC`](https://github.com/bazelbuild/rules_swift/blob/32001f34b291c00435e151c5c0d990a514e6eefd/third_party/com_github_grpc_grpc_swift/BUILD.overlay#L37-L56) target, we've hit an interesting issue. Building it results in this error:

```
ERROR: .../BUILD.bazel:78:1: Processing and signing CgRPCFramework failed (Exit 1)
replace bazel-out/darwin-fastbuild/bin/external/grpc_swift/CgRPCFramework_archive-root/CgRPC.framework/Headers/CgRPC.h? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Target @grpc_swift//:CgRPCFramework failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

Because the [unprocessed archive](https://github.com/bazelbuild/rules_apple/blob/f92ca9dff623caac6598c624e44823f972a9e91f/tools/bundletool/process_and_sign.sh.template#L13) ends up with 2 headers:

```
CgRPC.framework/CgRPC
CgRPC.framework/Headers/cgrpc.h
CgRPC.framework/Headers/CgRPC.h
CgRPC.framework/Modules/module.modulemap
```

This is because of the framework name I'm producing (CgRPC) and their default header being [`cgrpc.h`](https://github.com/grpc/grpc-swift/blob/d5f0c46e4fd067588d17f57894b8b0630c9daca1/Sources/CgRPC/shim/cgrpc.h)

**Comment by keith** [comment]
Maybe one solution for this case would be to allow users to provide the name of the umbrella header in the framework, and use that in the `module.modulemap` therefore removing the need to create a `CgRPC.h`.

**Comment by keith** [comment]
Another temporary workaround for this case is renaming the header with a genrule:

```python
genrule(
    name = "main-header",
    srcs = ["Sources/CgRPC/shim/cgrpc.h"],
    outs = ["cgrpc-main.h"],
    cmd = "cp $< $@",
)
```

Which results in:

```
CgRPC.framework/
CgRPC.framework/Headers/
CgRPC.framework/Headers/cgrpc-main.h
CgRPC.framework/Headers/CgRPC.h
CgRPC.framework/CgRPC
CgRPC.framework/Modules/
CgRPC.framework/Modules/module.modulemap
```

**Comment by thomasvl** [comment]
Shouldn't #359 cover this specific case since there is only one header?

**Comment by keith** [comment]
Thanks for the link! I commented there, but we might want to still solve this another way since you could hit this case with more headers as well

**Comment by sergiocampama** [comment]
Would it be easier to change the name of the target? Or use the `bundle_name` attribute in `ios_static_framework`?

**Comment by keith** [comment]
Definitely an option, in our case we'd prefer to keep the "correct" CgRPC name for the framework

**Comment by keith** [comment]
This is fixed by https://github.com/bazelbuild/rules_apple/pull/437
