### ISSUE TITLE
BundleTreeApp fails when sandboxed

### ISSUE THREAD

**Issue by FuegoFro** [bazelbuild/rules_apple#446]
Tulsi seems to compile using this experimental(?) `BundleTreeApp` action, which fails with
```
security: cert import failed: UNIX[Operation not permitted]
security: problem decoding
```
When I add `--strategy=BundleTreeApp=standalone` it's able to compile correctly. Similarly, when I run the full sandbox command that's output with `--sandbox_debug` it fails in the same manner, but if I remove the `/usr/bin/sandbox-exec -f .../sandbox.sb` prefix from the actual command part it works correctly.

**Comment by keith** [comment]
Can you test this with https://github.com/bazelbuild/rules_apple/pull/436

**Comment by FuegoFro** [comment]
Sorry for the slow response! That did indeed work 😀
