### ISSUE TITLE
Support Info.plist variable substitution for DEVELOPMENT_LANGUAGE variable

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#451]
`DEVELOPMENT_LANGUAGE` is a variable that is the default value for `CFBundleDevelopmentRegion` when create a new iOS project from one of of default Xcode template. This variable is currently not one of the supported variable substitutions, that would make the build fail if we don't manually edit the `Info.plist` file and replace `$(DEVELOPMENT_LANGUAGE)` with `en`.

Would it be possible to support the substitution for this variable? I suggest adding a new `development_language` or `development_region` attribute to the `ios_application` rule and substitute `DEVELOPMENT_LANGUAGE` to this attribute value when handling the `Info.plist` file.

**Comment by sergiocampama** [comment]
In order to support Info.plists out of the box coming from Xcode, our plan is to hardcode this variable to `en` and make sure it is noted in the rules documentation.

**Comment by thii** [comment]
Was it already one internally? If not, may I take it? 🙂

**Comment by sergiocampama** [comment]
Thanks!
