### ISSUE TITLE
iPadOS support

### ISSUE THREAD

**Issue by xinzhengzhang** [bazelbuild/rules_apple#457]
Since iPadOS and iPad app for mac was introduced in wwdc2019.
Is there any plan for supporting these two application rules?

**Comment by keith** [comment]
It's nice to have an issue tracking this but can you enumerate the specific issues where new support must be added?

**Comment by xinzhengzhang** [comment]
It makes possible for publishing app into Mac with single code base with UIKit.

Check out Introducing iPad Apps for Mac from #WWDC19

**Comment by thomasvl** [comment]
I don't think that is tied to an iPadOS sdk, as much as a bunch of other settings going into the project.

**Comment by xinzhengzhang** [comment]
I think the support for iPadOS is not just for capturing “new things” it is mainly for macOS.

I agreed that there should be a bunch of other settings going into the project. But it seems much benefit for developers develop macOS app using UIKit instead of AppKit. Not to mention mostly we can use the most of the same code for both iOS and macOS.
