### ISSUE TITLE
Allow output of bundling rules to be the bundle directory instead of IPA/ZIP

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#49]
[Tree artifacts](https://github.com/bazelbuild/bazel/blob/511c35b46cead500d4e76706e0a709e50995ceba/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleContext.java#L922) are available experimentally in Bazel, so we should be able to have the output of the bundling rules be the bundle itself (e.g., a `.app` folder) instead of an IPA or ZIP file.

This will speed up the bundling by not requiring files to be zipped/unzipped internally, and then tools like Tulsi can use the output directory instead of unzipping the final archive as well.

We could try implementing this early with an experimental `--define` to control whether it's used or not.

**Comment by sergiocampama** [comment]
This is available through the `--define=apple.experimental.tree_artifact_outputs=1` flag.

**Comment by joprice** [comment]
I tried this out, but needed to disable it for tests, otherwise I got an error that it was unable to find the zip file of the archived app.

```bash
build --define=apple.experimental.tree_artifact_outputs=1
test --define=apple.experimental.tree_artifact_outputs=0
```

**Comment by sergiocampama** [comment]
Closing as fixed, since tests now support bundle outputs
