### ISSUE TITLE
swift_library with objc_library deps

### ISSUE THREAD

**Issue by lswith** [bazelbuild/rules_apple#51]
It seems that the swift_library doesn't link the objc_library's correctly when they are a dependency.

**Comment by lswith** [comment]
An Example would be:
```
# In an External Workspace @Hello
objc_library(
    name = "Hello",
    srcs = glob([
        "Hello/*.m",
    ]),
    hdrs = glob([
        "Hello.*.h",
    ]),
)
```
```
# In My Current Workspace
swift_library(
     name = "GoodBye",
     srcs = glob([
          "GoodBye/*.swift",
     ]),
     module_name = "GoodBye",
     deps = [
         "@Hello//:Hello",
      ],
)
```

If in GoodBye I try to `import Hello` it will fail. The module name is actually `Hello_Hello`.

**Comment by dmishe** [comment]
This is correct, though not well documented. Module names, by default, are full target labels with any non [a-zA-Z0-9] character replaced with "_". That is how `@Hello//:Hello` gets translated into `Hello_Hello`

**Comment by lswith** [comment]
can we add the ability to define a module name for these objects?

**Comment by dmishe** [comment]
For `swift_library`, you can set your own `module_name`. For `objc_library`, not yet, that would be a feature request on Bazel itself.

**Comment by lswith** [comment]
This is causing bugs with importing. An example would be this:
`Hello/BUILD`
```
objc_library(
    name = "Hello",
    srcs = ["Hello.m"],
    hdrs = ["Hello.h"],
    deps = [
        "//Goodbye",
    ],
)
```
`Goodbye/BUILD`
```
swift_library(
    name = "Goodbye",
    srcs = ["Goodbye.swift"],
    deps = [ 
        ":Goodbye_objc",
    ],
   module_name = "Goodbye",
)

objc_library(
    name = "Goodbye_objc",
    srcs = ["Goodbye.m"],
    hdrs = ["Goodbye.h"],
)
```

This causes the bug inside the Hello module:
```
bazel-out/darwin_x86_64-fastbuild/genfiles/Goodbye/Goodbye-Swift.h:138:9: fatal error: module 'Goodbye_Goodbye_objc' not found
```

**Comment by lswith** [comment]
any updates on this?

**Comment by dmishe** [comment]
lswith, could you paste the contents of Goodbye-Swift.h?

**Comment by lswith** [comment]
I have a better idea. Here is the full sample for you to run:
https://github.com/lswith/bazel-ios-test

You can run from the hello folder. It doesn't compile
