### ISSUE TITLE
swift_library transistive dependencies

### ISSUE THREAD

**Issue by lswith** [bazelbuild/rules_apple#52]
The `swift_library` includes all of its transitive dependencies. This can have nasty problems later on.

**Comment by allevato** [comment]
Can you provide more detail about what you mean?

**Comment by lswith** [comment]
Currently I have a swift library A which depends on libraries B, C, D.

Library B also depends on C, and D.

In the swift_library build file for A, i only needed to put library B as a
dependency because B's dependencies were linked in automatically.

This means that if later on, B's dependencies change to C, and E, library A
will fail to build because of missing dependencies. This is a nasty place
to be in.

**Comment by allevato** [comment]
Ah, so something along the lines of [`strict_deps`](https://bazel.build/versions/master/docs/skylark/lib/java_common.html#compile) in Java.

@dmishe, would it make sense to update `swift_library` to only pass the .swiftmodules of its direct deps to `swiftc`?

**Comment by dmishe** [comment]
I think originally the reason we propagate everything was this.

Given target A > B >C. Where B has imports to C, and A has imports of B. In order to compile A, the compiler needs to see the module for C. If that's not the case, then we could reduce the set to direct deps, yep.

**Comment by dmishe** [comment]
I believe to solve the case of A, B, C, D suddenly breaking, we need to do what Bazel does with java's strict_deps. Specifically, the compiler should be instrumented to return all required deps to bazel, which will then validate that you depend on the modules you import. 

This will effectively prevent you from accidentally fulfilling the dependencies through other targets, while technically not being strict in terms of propagation.

**Comment by allevato** [comment]
> Given targets A > B > C. Where B has imports to C, and A has imports of B. In order to compile A, the compiler needs to see the module for C. If that's not the case anymore, then we could reduce the set to direct deps, yep.

Good point—I don't know the answer to that. I would imagine that it still needs C's module to know what symbols exist there, since A could use any public interface of B that involves C's symbols.

The post-validation step seems like the better approach, if there's a way we can get that information from the compiler today (without having to patch it—or just patch it but have it take longer to get in our hands).

**Comment by sergiocampama** [comment]
Closing since `swift_library` has been moved to [`rules_swift`](github.com/bazelbuild/rules_swift)
