### ISSUE TITLE
No Symbols directory in IPA

### ISSUE THREAD

**Issue by FuegoFro** [bazelbuild/rules_apple#545]
When Xcode produces an IPA, at the top level of the archive (eg a sibling of the `Payload/` directory) is a `Symbols/` directory. It seems that this directory is what powers App Store Connect's "Includes Symbols" status as well as the "Download dSYM" button.

However, IPAs produced by `ios_application` don't have this directory and therefore App Store Connect doesn't find symbols for uploaded builds, nor can it (re)provide dSYM files. I'm using the `--apple_generate_dsym` flag and have the dSYM files produced by that, but for parity with Xcode it would be nice to be able generate the `Symbols/` directory.

**Comment by sergiocampama** [comment]
We should be able to add a new flag to be used alongside `--apple_generate_dsym` to include the transitive dSYM bundles into the IPA.

**Comment by liuliu** [comment]
Do we know how these `*.symbols` file generated? These seems to be some kind of processed dsym files, but I am not sure how. With that knowledge, we should be able to modify the ipa to include these.

**Comment by thii** [comment]
```
xcrun symbols '-noTextInSOD' '-noDaemon' '-arch' 'all' '-symbolsPackageDir' 'Symbols' /path/to/dsym/binary
```
