### ISSUE TITLE
objc_framework not bundled correctly into ios_application

### ISSUE THREAD

**Issue by lswith** [bazelbuild/rules_apple#59]
I have an `ios_application` which relies on RxCocoa: https://github.com/ReactiveX/RxSwift. 

I have downloaded the .framework file from its releases: [3.4.1](https://github.com/ReactiveX/RxSwift/releases/download/3.4.1/RxSwift.framework.zip) and tried adding a build file as follows:
```
package(default_visibility = ["//visibility:public"])

objc_framework(
    name = "RxCocoa",
    framework_imports = [
        "Carthage/Build/iOS/RxCocoa.framework"
    ],
    is_dynamic = 0,
)
```

This causes the error at application runtime:
```
dyld: Library not loaded: @rpath/RxCocoa.framework/RxCocoa
  Referenced from: /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/480214EA-7464-4111-A88A-A2D5DC468785/data/Containers/Bundle/Application/EB21E332-5A4F-4953-BE43-F2A97CB6EB40/[REDACTED]Example.app/FLComponentExample
  Reason: image not found
```

If I change `is_dynamic` to 1, I get this error at compile time:
```
Showing All Messages
  (exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=10.3 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer\
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk\
    XCODE_VERSION_OVERRIDE=8.3.2 \
    bazel-out/darwin_x86_64-dbg/bin/[REDACTED]/[REDACTED]Example.process-and-sign.sh)

Use --sandbox_debug to see verbose messages from the sandbox.

bazel-out/darwin_x86_64-dbg/bin/[REDACTED]/[REDACTED]Example.archive-root/Payload/[REDACTED]Example.app/Frameworks/RxCocoa.framework: bundle format unrecognized, invalid, or unsuitable
```

Note:
This framework contains both objc and swift modules.

**Comment by lswith** [comment]
This also seems to be the case for the RealmSwift framework as well. https://static.realm.io/downloads/swift/realm-swift-2.7.0.zip

**Comment by sergiocampama** [comment]
`objc_framework`'s `framework_imports` expects a list of paths, which are all the files inside `RxCocoa.framework`. Can you try using `glob(["Carthage/Build/iOS/RxCocoa.framework/**"])` instead?

**Comment by lswith** [comment]
that fixed the problem! I think an example should be put in the docs for others.

**Comment by allevato** [comment]
The `objc_framework` rule should be retired completely (since it's native) and replaced with a Skylark-based rule in this repository instead. All it does it propagate files in an `ObjcProvider`, which AFAIK doesn't require any of the native machinery (I'll have to double check).

If that's the case, we can add proper documentation there, because we'd want to differentiate pre-built frameworks like this from `ios_framework`, which *builds* a framework from sources/resources.

I'll close this issue out for now, since the original question was resolved.

**Comment by lswith** [comment]
that makes sense. Thanks for the update.
