### ISSUE TITLE
Set up Bazel continuous integration

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#60]
We need to get our integration tests running on Bazel CI and hooked into pull requests. Also, get the little badges in our README that show the current build status.

**Comment by jgavris** [comment]
+1

**Comment by jgavris** [comment]
Is this on the roadmap in the short term?

**Comment by allevato** [comment]
Short-term, probably not. It's one of those tasks that we'd like to get done to make sure the pushes from our internal codebase are stable (even after we run our own CI), but it's not as high priority as some of the other work we have to do.

**Comment by thomasvl** [comment]
Closing this, #135 adding travis support since it let us get trunk and a release bazel.
