### ISSUE TITLE
Consider bazel query when picking rule names

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/rules_apple#624]
We noticed recently that `kind(ios_unit_test, ...)` will return both `ios_unit_test` and `ios_unit_test_bundle`. We can avoid it by changing the query to `kind("ios_unit_test rule", ...)` but I wonder if the best thing to do is pick names that avoid such collisions, where possible. Since `ios_unit_test_bundle` is internal, it could have a name like `_ios_internal_unit_test_bundle`, etc.

**Comment by thomasvl** [comment]
The behavior of `kind()` sorta sucks being a prefix match.  Anyway, yes, since we currently don't plan on making that bundle/rule api we intend to support a leading prefix of underscore would probably be a good thing; along with keeping this in mind for other things in the future.
