### ISSUE TITLE
Support for watchOS static framework

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#630]
Is there any plan to support building watchOS static framework? We have a use case for this but are still having to use `xcodebuild` for it.

My impression is that the implementation could derive a lot from `ios_static_framework` and `tvos_static_framework` rules.

**Comment by sergiocampama** [comment]
so far no one else has requested the rule, so we didn't have plans for them. it should follow the same implementation as `tvos_static_framework`, would you be willing to provide a PR for this?

**Comment by thii** [comment]
I'll take a look.

**Comment by thii** [comment]
Resolved by https://github.com/bazelbuild/rules_apple/pull/1008.
