### ISSUE TITLE
Error while building apple app with bazel

### ISSUE THREAD

**Issue by salim-boudriiya** [bazelbuild/rules_apple#631]
Hi @sergiocampama ,

I am working on a project to build ios applications (written in swift).

I have started a simple example, where I have two libraries, made with swift, and I want to link them using the dep tag.

But I have the following error when I want to import one class into another.

bazel build IosProjects
INFO: Analyzed target //ios:IosProjects (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/smba/repo/IOS/ios/molecule1/BUILD:8:1: Compiling Swift module ios_molecule1_moleculeSource1 failed (Exit 1)
ios/molecule1/Sources/Molecule1.swift:10:8: error: no such module 'Atom1'
import Atom1
       ^
Target //ios:IosProjects failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.831s, Critical Path: 1.68s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

I attach the two build files:

**### Build file of Atom:**

package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("//apple:ios.bzl", "ios_static_framework")

licenses(["notice"])

        
swift_library(
    name = "atomSource1",
    srcs = [
        "Sources/Atom1.swift",
    ],
)

ios_static_framework(
    name = "atom1",
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = "8.0",
    deps = [":atomSource1"],
)

**### Build file of Molecule:**

package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("//apple:ios.bzl", "ios_static_framework")

licenses(["notice"])

swift_library(
    name = "moleculeSource1",
    srcs = [
        "Sources/Molecule1.swift",
    ],
    deps = ["//ios/Atom1:atomSource1"]
    
)

ios_static_framework(
    name = "molecule1",
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = "8.0",
    deps = [":moleculeSource1"],
)

Can you help me to resolve it please

Best regards.

**Comment by sergiocampama** [comment]
I see 2 issues here:

1. `ios_static_framework` does not support `swift_library` targets that have transitive `swift_library` dependencies.
1. The name of the module for hthe `atomSource1` target is not `Atom1`. You can make it be that by setting the `module_name = "Atom1",` attribute on `atomSource`, but otherwise, the module name will be the `<path_to_BUILD_with_/_replaced_by_underscores>_<target_name>`
