### ISSUE TITLE
When bulding a resources bundle, should add plist if there are images. 

### ISSUE THREAD

**Issue by mpalczew** [bazelbuild/rules_apple#639]
Adding images to a resources framework doesn't work as expected. In theory I expect to be able to do this. 
```
apple_resource_bundle(
    name = "Resources",
    bundle_name = "MyResources",
    resources = glob([
        "Assets/**",
        "Images.xcassets/**"
    ]) 
)
```

Then I should be able to add it to my app and do something like. 
```
let bundle: Bundle = .init(url: Bundle.main.url(forResource: "MyResources, withExtension: "bundle"))
let image = Image(named: "MyImage", in: bundle, compatibleWith: nil)
```
This fails. 

I have to do the following. 

```
apple_resource_group(
    name = "Images",
    resources = glob(["Images.xcassets/**"]),
)

apple_resource_bundle(
    name = "Resources",
    bundle_name = "MyResources",
    infoplists = ["Resources.plist"],
    resources = glob([
        "Assets/**",
    ]) + [":Images"],
)
```

1. I have to make a resources group first. Even though I didn't put these in structured resources.  This will end up created the Assets.car file where images load. 
2. I have to add a plist or no images will load from this bundle.

**Comment by thomasvl** [comment]
Can you provide an example directory structure that shows the problem?

It could be that there is a bug if you are using things at the root of your WORKSPACE vs. down a level.

**Comment by mpalczew** [comment]
I'll get you a tarball.
