### ISSUE TITLE
plisttool failes on unknown variable reference $PRODUCT_BUNDLE_PACKAGE_TYPE

### ISSUE THREAD

**Issue by ghost** [bazelbuild/rules_apple#643]
## Description
A new Info.plist variable has been defined recently [here](https://forums.developer.apple.com/thread/123573) and ios_application rule failes on Info.plist that includes it. 

I am new to Apple and rules_apple, so not sure how to workaround it or contribute a fix. But if I figure, I will try to contribute. If I can have a mentor, I am happy to help as well. 

## Environemnt 
```
...
	<key>CFBundlePackageType</key>
	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
...
```

## Expected behaviour
Build runs without a problem

## Observed error
```
ERROR: In target "//test_app:app"; unknown variable reference "$(PRODUCT_BUNDLE_PACKAGE_TYPE)" while merging plists (key: "CFBundlePackageType", value: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)").
```

**Comment by Sythanis** [comment]
Took a Info.plist file from a default generated project from xcode 11.1.0 . Not sure if `CFBundlePackageType` key value pair is important property for rules_apple.

**Comment by keith** [comment]
A quick fix for this on your side would be to change your plist to hardcode the right value. It would be useful to know what this is used for and what the possible values are.

**Comment by thomasvl** [comment]
I believe we do document all the subs we support: https://github.com/bazelbuild/rules_apple/blob/master/doc/common_info.md#variable-substitution

Looks like it might be something completely new in Xcode 11 - https://forums.developer.apple.com/thread/123573

**Comment by ethanyanjiali** [comment]
This comes by default in XCode 12, I end up deleting
```
<key>CFBundlePackageType</key>
<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
```

**Comment by brentleyjones** [comment]
Looks like we fixed this with https://github.com/bazelbuild/rules_apple/pull/891. Please reopen if that's not the case.
