### ISSUE TITLE
Having trouble setting up app_icons for iOS

### ISSUE THREAD

**Issue by yuriy-yarosh** [bazelbuild/rules_apple#657]
For some reason bazel doesn't pick up icons generated with the respective [fastlane](https://github.com/fastlane-community/fastlane-plugin-appicon). 

I'm using the following config
```
ios_application(
    app_icons = glob(["App/Sources/WhiteLabel/AppIcon.xcassets/**"] , exclude=["**/*.DS_Store"]),
    name = "App",
    version = ":app_version",
    bundle_id = "io.bitsnap.app",
    resources = [
        "//App/Sources/Themes:resources",
        "//App/Sources/Screens:resources",
        "//App/Sources/WhiteLabel:icons"
    ],
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = min_ios_version,
    provisioning_profile = "//App/Profiles:App.mobileprovision",
    launch_storyboard = "//App/Sources/WhiteLabel:Launch.storyboard",
    infoplists = ["Sources/Info.plist"],
    deps = [
        "//App/Sources/WhiteLabel"
    ]
)
```

But it doesn't pick up the respective icons folder, although compiles and bundles pretty much ok otherwise.

Icon names are corresponding to the `Contents.json` file generated by the fastlane plugin ...
```
...
 {
      "size": "29x29",
      "idiom": "ipad",
      "filename": "App-29x29.png",
      "scale": "1x"
    },
    {
      "size": "20x20",
      "idiom": "ipad",
      "filename": "App-20x20.png",
      "scale": "1x"
    }
...
```

I'm using latest rules_apple.

Yup, I've tried all the wildcards.

**Comment by thomasvl** [comment]
Your `glob` looks invalid, you likely need `App/Sources/WhiteLabel/AppIcon.xcassets/**` to actually match the files recursively.  Likewise, the `exclude` should probably be `"**/.DS_Store"` to match them at any location.

**Comment by yuriy-yarosh** [comment]
Yup @thomasvl thanks for attention.
I've tried it both ways, cleaned, deleted the bazel-out folder ... no luck.

**Comment by thomasvl** [comment]
As long as there is a real asset catalog with icons in that glob, it should work.  If you can post a minimal testcase that shows the failure someone can try to help look but for what's posted, it seems like it should work.

**Comment by yuriy-yarosh** [comment]
I've tried building the TestApp and it runs `actool` correctly... while my build doesn't run actool at all for the app_icons folder I've set. Will investigate further.

**Comment by thomasvl** [comment]
Actually, looks like you are mixing concepts.  You have a bunch of labels for other things that start `//App/Sources`, but your glob also has `App/Sources`.  Where is this BUILD file and are you using the correct relative path to the assets from that directory?

**Comment by yuriy-yarosh** [comment]
@thomasvl the target BUILD file is in App dir.
I've changed the glob to "Sources/WhiteLabel/AppIcon.xcassets/**"  but it didn't work.
So... I've moved `AppIcon.xcassets` to `App` and it did work with respective `AppIcon.xcassets/**` glob.

It puzzles me a bit, because `WhiteLabel` is a package too, and I've tried exporting AppIcon.xcassets as LaunchScreen.storyboard ... 

So, It've actually worked with filegroup wrapped glob and proper visibility in the end.

`glob(["Sources/WhiteLabel/AppIcon.xcassets/**"])` didn't work even though WhiteLabel has `package(default_visibility = ["//visibility:public"])`.

**Comment by thomasvl** [comment]
> @thomasvl you might consider adding some checks regarding globs matching 'cause it may not pick up the respective files from the subpackage even though glob had matched 'em correctly.

Rules can't do anything about that.  That's a Bazel thing.  By the time the rule comes into play we get the result of the glob - nothing when it goes wrong, which is the same as if you didn't bother setting anything.
