### ISSUE TITLE
Validate the format of the bundle_id attribute

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#7]
Validate the `bundle_id` attribute early in the rule to make sure that it's well-formed. (This is separate from the validation already being done between apps and extensions). We would reject bundle IDs that have, for example, spaces in them.

**Comment by thomasvl** [comment]
https://github.com/bazelbuild/rules_apple/blob/master/apple/bundling/bundling_support.bzl#L256 is called from the bundling rule, so this is done now.
