### ISSUE TITLE
Add bundle_name attribute to all bundling rules to override target name

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#70]
Sometimes you don't want to use the target's name as the bundle's name, so we should add an optional `bundle_name` attribute that lets the user override that.

For example, currently this produces `Foo.app` and it can't be changed:

```python
ios_application(
    name = "Foo",
    ...
)
```

So we should add this to get `SomethingOtherThanFoo.app` (note that the extension is still determined by the rule):

```python
ios_application(
    name = "Foo",
    bundle_name = "SomethingOtherThanFoo",
    ...
)
```

**Comment by rahul-malik** [comment]
@allevato - Any sense of when this might be available? I'm currently trying to build a workaround at the moment for this issue.

**Comment by allevato** [comment]
@rahul-malik This is done now in master for applications/extensions/frameworks. It won't work yet for `objc_bundle_library` targets.
