### ISSUE TITLE
bundletool zips break code signing

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_apple#737]
Reproducing the command line from rules_apple:

```
/usr/bin/codesign -v --sign - --force qtox_archive-root/qtox.app/Contents/Frameworks/QtCore.framework
qtox_archive-root/qtox.app/Contents/Frameworks/QtCore.framework:
 bundle format is ambiguous (could be app or framework)
```

The reason for this is that qtox.app has been zipped and unzipped, which resolved all the symlinks. Apparently, codesign depends on those symlinks to determine what kind of thing it is it's supposed to sign.

**Comment by keith** [comment]
Closing for https://github.com/bazelbuild/rules_apple/issues/1040 since it has more info

**Comment by muizidn** [comment]
In case someone stumbled upon this issue, I confirm this symlink requirement by replacing `bazel unzipped imported framework` with `actual framework` and codesigning works perfectly.

**Comment by HachikoLIU** [comment]
As mentioned by apple:
The framework bundle structure is different from iOS.
The symbol links are required by apple in framework bundle , and are verified through codesign and notarization process.
Is there any approach to import framework on MacOS?
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html
