### ISSUE TITLE
Feature request: add an option to disable code signing.

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_apple#738]
See https://github.com/bazelbuild/rules_apple/issues/737. I was able to get my build to work by disabling code signing deep in rules_apple, but that requires me carrying around a patch. It would be good if I could disable code signing altogether until #737 is fixed.

**Comment by keith** [comment]
I don't think we'll do this outside of some performance optimizations https://github.com/bazelbuild/rules_apple/pull/958

we should fix your linked bug instead

**Comment by MuzahidGithub** [comment]
> See [#737](https://github.com/bazelbuild/rules_apple/issues/737). I was able to get my build to work by disabling code signing deep in rules_apple, but that requires me carrying around a patch. It would be good if I could disable code signing altogether until [#737](https://github.com/bazelbuild/rules_apple/issues/737) is fixed.

Can you share the rules to disable code signing
