### ISSUE TITLE
Support custom executable name

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#762]
Currently the executable name of rules that create executables (`*_application`) always has the same value as the value of `bundle_name` attribute. Although it's possible to change the executable name by just changing the bundle name, it would also change the name of the artifacts depending on that (for instance, `.app` and `.app.dSYM`)—this is error-prone if you want to do something with them (for instance, `ipa_post_processor` does not accept any parameter).

I’d like to request to add a new attribute `executable_name` to rules that create executables to allow specify custom executable name in the final bundle. This could be an optional attribute that, if not specified, will get the value of `bundle_name` or `name` in this order. 

The motivations are:
* With Xcode, we have different executable names for each build configuration—that makes it possible to filter logs using the macOS' Console app using the process name, when you have multiple configurations of the same app installed on the same device.
* Being able to keep the conventions closer to what Xcode allows (same bundle name, but different executable name)

I can try to come up with a patch if this is accepted. Thanks!

**Comment by thii** [comment]
@keith Would you accept a patch for this?

**Comment by segiddins** [comment]
I think this makes sense to me, especially since it's easily configured in Xcode today.
