### ISSUE TITLE
UIImage(named: in: compatibleWith:) returning nil when using apple_resource_bundle

### ISSUE THREAD

**Issue by acecilia** [bazelbuild/rules_apple#765]
Hi:

I am having a problem using `.xcassets` when using `apple_resource_bundle`.

I successfully create a resources bundle with `apple_resource_bundle` which contains an `.xcassets` with an `icon.png` image. When I test with bazel I can see that the `.bundle` is generated with a `Assets.car` inside, and using https://github.com/insidegui/AssetCatalogTinkerer I can verify that the image I placed in the `.xcassets` is there.

The problem is that doing `UIImage(named: "icon", in: bundle, compatibleWith: nil)` always returns nil.

I already tried recreating the `.xcassets` trying `png` and `pdf`, disabling sandbox, different glob syntax... But still the problem persists. 

Any help is much appreciated.

I made a sample project here: https://github.com/acecilia/bazel-sample
Just do:

```
git clone https://github.com/acecilia/bazel-sample.git
cd bazel-sample
bazel test //...
```

You will see the test failing due to `UIImage` returning nil.

My `BUILD.bazel`:

```bazel
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application", "ios_unit_test")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@build_bazel_rules_apple//apple:resources.bzl", "apple_resource_bundle")

# Swift Library

tags = ["no-sandbox"]

swift_library(
  name = "Library",
  srcs = glob(["Library/srcs/main/src.swift"]),
  tags = tags,
  visibility = ["//visibility:public"],
)

apple_resource_bundle(
  name = "LibraryTestResources",
  bundle_name = "LibraryTests",
  resources = glob([
    "Library/resources/images.xcassets/**",
  ]),
  tags = tags,
  visibility = ["//visibility:public"],
)

swift_library(
  name = "LibraryTestLib",
  srcs = glob(["Library/srcs/test/test.swift"]),
  deps = [":Library"],
  data = [":LibraryTestResources"],
  tags = tags,
  visibility = ["//visibility:public"],
)

ios_unit_test(
  name = "LibraryTests",
  deps = [":LibraryTestLib"],
  minimum_os_version = "11.0",
  test_host = "//:HostApp", 
  tags = tags,
  visibility = ["//visibility:public"],
)

# Host app

swift_library(
  name = "HostAppLib",
  srcs = glob(["Support/AppDelegate.swift"]),
  tags = tags,
  visibility = ["//visibility:public"],
)

ios_application(
  name = "HostApp",
  bundle_id = "HostApp",
  families = ["iphone"],
  infoplists = glob(["Support/Info.plist"]),
  minimum_os_version = "11.0",
  deps = [":HostAppLib"],
  tags = tags,
  visibility = ["//visibility:public"],
)
```

My code:

```swift
import XCTest
import Library
import UIKit

class Tests: XCTestCase {
    func test() {
        let bundle = Bundle(url: Bundle(for: Tests.self).url(forResource: "LibraryTests", withExtension: "bundle")!)!
        print(bundle.bundlePath)

        let image = UIImage(named: "icon", in: bundle, compatibleWith: nil)
        print(image)

        XCTAssertNotNil(image)
    }
}
```

I am using bazel 3.0.0 and a recent version of the rules: https://github.com/acecilia/bazel-sample/blob/master/WORKSPACE

Thank you :)

**Comment by acecilia** [comment]
Well, this is shocking: apparently xcassets are buggy and they can not be used inside resource bundles: https://stackoverflow.com/a/23903860

**Comment by bigbangvn** [comment]
hi @acecilia do you still need to use the workaround of adding info.plist, I'm having similar issue
