### ISSUE TITLE
Validate CFBundleVersion and CFBundleShortVersionString

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#8]
`Info.plist` processing should validate the version values that end up in the final plist and cause a build failure if they are invalid.

Unfortunately, [Apple's own documentation](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html) isn't quite consistent with what they actually accept in submissions, so doing this correctly is a bit trickier than it should be. We don't want to have false positives or false negatives.

**Comment by thomasvl** [comment]
This is now done.

Regexes and notes: https://github.com/bazelbuild/rules_apple/blob/master/apple/bundling/bundling_support.bzl#L256

The methods: https://github.com/bazelbuild/rules_apple/blob/master/apple/bundling/bundling_support.bzl#L256
