### ISSUE TITLE
macos_command_line_application doesn't appear to support Runfiles

### ISSUE THREAD

**Issue by warriorstar-orion** [bazelbuild/rules_apple#813]
```
$ uname -a
Darwin eikthyrnir.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
$ bazel --version
bazel 3.2.0-homebrew
```

Reproduce: clone https://github.com/warriorstar-orion/bugs_macos_cliapp_runfiles

```
$ bazel run @bugs_macos_cliapp_runfiles//:main
INFO: Analyzed target //:main (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 0.067s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Unable to open file /private/var/tmp/_bazel_warriorstar/4916f64786f480ceec305b3fc8f10854/execroot/bugs_macos_cliapp_runfiles/bazel-out/darwin-fastbuild/bin/main.runfiles/bugs_macos_cliapp_runfiles/test.txt
```

While I understand most Mac apps have systems involving bundling resources, I'd like the application I'm writing to be "roughly" cross-platform, without having to write a layer over managing asset files.

Let me know if I can provide additional information.

**Comment by thomasvl** [comment]
Drive by - given you want it to be "cross-platform", why use the Apple specific rules?  `cc_library` and `cc_binary` likely will just work and get you the support you are looking for.  The helper for runfiles is also part of a class you are directly pulling form the cc rules.

**Comment by warriorstar-orion** [comment]
Hmm, I was having some issues with using cc_binary on MacOS. I think it was due to incorrectly configured constraints. I think that'll work for my purposes.
