### ISSUE TITLE
Support for App Clips

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/rules_apple#821]
App Clips are similar to App Extensions, except they are full apps: https://developer.apple.com/documentation/app_clips/creating_an_app_clip.

We should have rules for creating App Clips and embedding them in `ios_application` targets.

**Comment by brentleyjones** [comment]
I know we will personally need this relatively soon, and i can work on putting together a patch for this.

**Comment by xiemotongye** [comment]
My team will face with the same problem in the near future. New rules should be created for  App Clips.

**Comment by brentleyjones** [comment]
I plan on starting work on this soon (start of next week at the earliest, because of the short holiday week here in the US).

**Comment by brentleyjones** [comment]
I have the rules working locally. I'll clean them up and open a PR early next week.

**Comment by brentleyjones** [comment]
I've opened a PR: #838

**Comment by brentleyjones** [comment]
Resolved with https://github.com/bazelbuild/rules_apple/pull/916.
