### ISSUE TITLE
Support building Widget Extensions

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#841]
Widget Extensions use SwiftUI's `@main` attribute to specify the entry point—it doesn't need the extra `-e _NSExtensionMain` linker flags, which are being hardcoded in the `ios_extension` macro.

https://github.com/bazelbuild/rules_apple/blob/c283c82941e9f7e58f5176b68850e6a91b68e956/apple/internal/rule_support.bzl#L233-L239

**Comment by keith** [comment]
Looks like https://github.com/bazelbuild/rules_apple/pull/842 fixes this

**Comment by allevato** [comment]
Yes it did! Add `provides_main = True` to any `ios_extension` or `macos_extension` that is a widget extension (and thus provides its own entry point).
