### ISSUE TITLE
Create a GitHub page for documentation

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#883]
This repo has a lot of useful documents but they're not searchable with Google. How about creating a GitHub page for documentation so it gets indexed by search engines?

Something similar to what `rules_rust` does: https://bazelbuild.github.io/rules_rust.

**Comment by thii** [comment]
Can you add the non-rules documentation too?

https://github.com/bazelbuild/rules_apple/blob/master/doc/common_info.md
https://github.com/bazelbuild/rules_apple/blob/master/doc/frameworks.md
https://github.com/bazelbuild/rules_apple/blob/master/doc/types.md

**Comment by alexeagle** [comment]
I see what happened, I was copying `docs/*.md` from each ruleset but not checking for `doc/*.md`
fixed now :)

**Comment by thii** [comment]
Thanks. Although I'd prefer something living within this repo, the original intent of the issue was to make those hand-written docs searchable to increase their visibility, I think I can close this now :) 

Thanks for putting a lot of work into the Stardoc fixes 👍
