### ISSUE TITLE
Allow apple_dynamic_framework_import to import dSYMs

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#892]
Following-up https://github.com/bazelbuild/rules_apple/pull/882, there’s current no API that allows to import user-provided dSYMs that come along with prebuilt frameworks. This makes rules_apple unable to generate `.symbols` files from user-provided dSYMs. This suggests adding a new attribute (`dsym_imports` or `data`) to `apple_{dynamic,static}_framework_import` to make that possible.

**Comment by keith** [comment]
Related https://github.com/bazelbuild/rules_apple/pull/869
