### ISSUE TITLE
Support for CFBundleIcons.CFBundleAlternateIcons

### ISSUE THREAD

**Issue by steeve** [bazelbuild/rules_apple#895]
This `Info.plist` key is used to implement alternate icons.

Unfortunately at this moment, trying to set that key will result in `plisttool.py` complaining when merging `CFBundleIcons`. So it seems not possible to use dynamic icons with `rules_apple` at this moment.

Example:
```xml
<key>CFBundleIcons</key>
<dict>
	<key>CFBundleAlternateIcons</key>
	<dict>
		<key>MyOtherIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>MyOtherAppIcon</string>
			</array>
			<key>UIPrerenderedIcon</key>
			<false/>
		</dict>
	</dict>
	<key>CFBundlePrimaryIcon</key>
	<dict>
		<key>CFBundleIconFiles</key>
		<array>
			<string>MyAppIcon</string>
		</array>
		<key>CFBundleIconName</key>
		<string>MyIcon</string>
	</dict>
</dict>
```

I was thinking about something like this:
```python
app_icon = glob(["Resources/Assets/AppIcon.xcassets/**"]),
alternate_icons = {
    "MyOtherIcon": glob(["Resources/Assets/OtherAppIcon.xcassets/**"]),
    "MyThirdIcon": glob(["Resources/Assets/ThirdAppIcon.xcassets/**"]),
},
```

**Comment by keith** [comment]
A current workaround is to add generate this plist with a custom rule and provide the icons as data. I wonder if making a separate rule like this would make more sense vs adding it to *application 🤔🤔

**Comment by steeve** [comment]
Another idea would be make `ios_application` a macro and make `app_icon` accept a dict when one wants alternate icons, with `""` or `None` as primary.

**Comment by steeve** [comment]
Actually, I just tried skipping the `app_icon` parameter, passing my own `Info.plist` and adding the icons as `resources`, `plisttool` still complains. Will look deeper a bit later.

Another short term solution is to do it during the post process phase.

**Comment by steeve** [comment]
Another weirdness, if our case, the `plist` was generated by Xcode and already contained icon definition like so (`AppIconEnterprise` is an `appiconset`):
```json
{
  "CFBundlePrimaryIcon": {
    "CFBundleIconFiles": [
      "AppIconEnterprise"
    ],
    "CFBundleIconName": "AppIconEnterprise"
  }
}
```

But the generated one by rules_apple looks like so:
```json
{
  "CFBundlePrimaryIcon": {
    "CFBundleIconFiles": [
      "AppIconEnterprise60x60"
    ],
    "CFBundleIconName": "AppIconEnterprise"
  }
}
```

Haven't had time to dig much though.

**Comment by steeve** [comment]
So I started working on this.

The bad news is all the intermediate `plists` are merged at the top level. This means that `CFBundleIcons.CFBundleAlternateIcons` needs to be generated in the same step as `CFBundleIcons.CFBundlePrimaryIcon`, which is generated by a call to `actool`.

Second issue, there is no such thing as `string_keyed_label_list_dict`, and we need a way to pass the icons `id` somehow.

I propose we introduce a `.alticon` directory, of which the name is the icon id, and containing the icons themselves. Unfortunately, asset catalogs and `appiconset` are not supported for alternate icons.

Then, those new `.alticon` files are passed to `xctoolrunner actool`, parsed, at after `actool` generates the icon information, manually add the alternate icons info too.

**Comment by steeve** [comment]
cc @brentleyjones

**Comment by brentleyjones** [comment]
@erikkerber @timhendricksen: Any thoughts on the above, since I know y'all need this as well?

**Comment by erikkerber** [comment]
(Too much time in GHE to see my GH notifications 😅)

That would work for us. Thanks for looking into this!

**Comment by steeve** [comment]
I finally have a working prototype. Draft PR probably in a few hours.

**Comment by steeve** [comment]
Draft PR opened at https://github.com/bazelbuild/rules_apple/pull/1032, feedback welcome.

**Comment by tinder-maxwellelliott** [comment]
I would love to see this landed! Thank you @steeve for the PR!

**Comment by steeve** [comment]
@tinder-maxwellelliott if you could test #1032 and let me know if it fits your use cases, I'll add what's missing to it

**Comment by steeve** [comment]
also cc @erikkerber

**Comment by erikkerber** [comment]
The `.alticon` directory might be a little confusing to anyone that doesn't know the backstory, but testing on my end seems to work well!

<img width="497" alt="Screen Shot 2021-01-19 at 11 00 00 PM" src="https://user-images.githubusercontent.com/75236/105129147-11880880-5aaa-11eb-968e-1f3f9f3278de.png">

<img width="134" alt="Screen Shot 2021-01-19 at 10 59 45 PM" src="https://user-images.githubusercontent.com/75236/105129132-07fea080-5aaa-11eb-93c9-ebb5c0d82693.png">

**Comment by erikkerber** [comment]
(Also big thanks – this is great to see working)

**Comment by tinder-maxwellelliott** [comment]
> @tinder-maxwellelliott if you could test #1032 and let me know if it fits your use cases, I'll add what's missing to it

I can take a look at this tomorrow. Thanks again!

**Comment by steeve** [comment]
Great, I'll finish the PR and hopefully we can merge this soon.

**Comment by tinder-maxwellelliott** [comment]
> Great, I'll finish the PR and hopefully we can merge this soon.

Sorry for the long delay. I am testing this today and can help verify

**Comment by tinder-maxwellelliott** [comment]
> Great, I'll finish the PR and hopefully we can merge this soon.

I am running into issues locally, what is the right way specify the `alticon` directories?

```
 alternate_icons = ["SomeApp/Dark.alticon", "SomeApp/International.alticon"],
```

or should these be `globs`?
