### ISSUE TITLE
AppleBinaryInfo providers should be listed in OutputGroupInfo

### ISSUE THREAD

**Issue by nikhilm** [bazelbuild/rules_apple#911]
I have a use case where I have

```
macos_dylib(
  name = "foo",
  ...
)

pkg_tar(
  ...
  srcs = [":foo"],
)
```
to package a dylib as part of a tar. When dsyms are enabled, this does the wrong thing as the dSYM also ends up in the tar, which i don't want.

I thought of using `filegroup()` with `output_group` to request a specific provider (the `AppleBinaryInfo` returned from macos_dylib), but since the AppleBinaryInfo is not advertised in the returned OutputGroupInfo, it cannot be retrieved in this way.

I'm working around this for now by having a custom rule that accesses the `AppleBinaryInfo` and returns a `DefaultInfo`, but it would be nice to fix this for all users and all of the Apple rules.

What would such a PR look like given the partials used? I'm happy to submit one with some guidance.

**Comment by keith** [comment]
Hrm, I guess it might be arguable whether or not you want the dSYMs in the tar, depending on your use case. Can you exclude those from your build, or with `--output_groups=-dsyms` instead (I haven't verified these would exclude them myself but I would assume so)?

**Comment by nikhilm** [comment]
That is an excellent point relevant to this. I realized after that using my custom rule won't really work.

The larger problem I'm trying to solve is:
- I do want the dsym to be generated, so it is important my overall build graph use the `DefaultInfo` so Bazel will actually generate the dsym.
- I don't want to put the dsym in the tar, since the tar effectively represents a bunch of files that I'm going to package into something to ship to customers.

This means `--output_groups=-dsyms`  isn't what I want either.

There is some potential for using something like https://github.com/bazelbuild/rules_pkg/issues/85, otherwise, for now, I've taken to just removing the file from the tar outside of Bazel, in a post-build step.

I'm not sure if rules_apple is the right place to solve something like this. Feel free to close this.

**Comment by keith** [comment]
Yea that all makes sense. As a short term workaround I would probably write my own pkg_tar rule (or use a genrule) and pick and choose the files you want from the final output (emulating the issue you linked).

I can definitely understand the use case here, but I don't have any good ideas on how this would fit in to rules_apple, it seems like the most likely medium term solution is for that issue to be resolved, but I'll leave this open in case others have ideas!

**Comment by nikhilm** [comment]
@keith to revive this, would it be possible to at least put `AppleBinaryInfo` into the `OutputGroupInfo` so that it would be possible to use that with `filegroup()`s `output_group` argument?
I think the `OutputGroupInfo` setup is done in some [common place](https://github.com/bazelbuild/rules_apple/blob/d8b905d75ef36e6c31f195b377070fcfd65d2652/apple/internal/processor.bzl#L540) right now, where the binary info is not available. How would one go about reconciling this to send a PR?

**Comment by brentleyjones** [comment]
Does #929 resolve this?

**Comment by keith** [comment]
Yep!
