### ISSUE TITLE
Adding Custom Code Signing Flags

### ISSUE THREAD

**Issue by michaeleisel** [bazelbuild/rules_apple#935]
I can't find any way to add code signing flags, what if we add one? Something flexible like `copts` and `linkopts` to add arbitrary flags. @keith this would allow for the `--resource-rules=...` trick we discussed to speed up code signing, along with other ones like `--digest-algorithm=sha1`

**Comment by keith** [comment]
Yea I think this would be nice to have. A bit weird since the use cases are so limited, but I agree for these 2 examples it would be great.

**Comment by michaeleisel** [comment]
| use cases are so limited

Is that a challenge to find more undocumented goodness? 😛

**Comment by michaeleisel** [comment]
PR here: https://github.com/bazelbuild/rules_apple/pull/942
