### ISSUE TITLE
method invocation returned None, please file a bug report: xcode_version().

### ISSUE THREAD

**Issue by perezd** [bazelbuild/rules_apple#95]
Got this message when I tried to bazel build a simple pure swift_library.

Bazel version details:
Build label: 0.5.2-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 27 20:24:06 2017 (1498595046)
Build timestamp: 1498595046
Build timestamp as int: 1498595046

rules_apple, included into workspace as: https://github.com/bazelbuild/rules_apple/archive/4ac137080708924f6da02f8165b1c53b99d2d1c7.zip

xcode-select -p prints:
/Applications/Xcode-beta.app/Contents/Developer
(Version 9 beta 3)

**Comment by perezd** [comment]
Also confirming same error when I installed Xcode 8.3.3 from App Store.

xcode-select -p reports:
/Applications/Xcode.app/Contents/Developer

**Comment by perezd** [comment]
looks like I can manually specify --xcode_version=8.3.3 and that causes it to work...shouldn't it be detectable?

**Comment by dmishe** [comment]
Can you copy the full build log when you see the error?

**Comment by perezd** [comment]
What is the best way to get that? Any special sub commands?

**Comment by dmishe** [comment]
Add a `-s` flag and pipe the output to a file. That's probably the easiest way.

**Comment by perezd** [comment]
This seems to have gone away after restarting. Must have been an XCode thing.
