### ISSUE TITLE
on macOS isysroot should be set to a stable execroot relative path

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/rules_apple#966]
### Description of the problem / feature request:

`isysroot` should be set to a stable exec root relative path (such as a symlink to the real Xcode SDK) to prevent the path of the build machine's Xcode from being embedded in build artifacts.

Currently `isysroot` is set to `__BAZEL_XCODE_SDKROOT__`, which currently resolves to something like `/Applications/Xcode-11.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk`. This causes paths like `/Applications/Xcode-11.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/dispatch` being embedded into artifacts when they contain debug symbols.

### Feature requests: what underlying problem are you trying to solve with this feature?

Making this change would make macOS debug or dSYM generating targets more reproducible.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On macOS:

```
bazel build --compilation_mode=dbg -- :some-objc-target
```

The `.o` files compiled will have embedded paths, generated by `DW_AT_LLVM_isysroot`, pointing to machine specific paths for Xcode.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 2.1.0

###  Have you found anything relevant by searching the web?

None

### Any other information, logs, or outputs that you want to share?

http://blog.llvm.org/2019/11/deterministic-builds-with-clang-and-lld.html

> You then need to modify your build files to use --sysroot (Linux), -isysroot (macOS), -imsvc (Windows) to use these hermetic SDKs for builds. They need to be somewhere below your source root to not regress build directory name invariance.

**Comment by keith** [comment]
These features should fix this https://github.com/bazelbuild/bazel/pull/12175 https://github.com/bazelbuild/rules_swift/pull/511

Note with Swift there was a bug where debug-prefix-map didn't apply to sysroot, it has been fixed but not made it to Xcode yet.
