### ISSUE TITLE
Configuring -target x86_64-apple-ios7.0 in swift_library?

### ISSUE THREAD

**Issue by perezd** [bazelbuild/rules_apple#97]
Wondering how to control that target value. From looking at the code, its reading _swiftc_target which is reading apple_fragment. What controls these values? I'm trying to build a library for a macos binary.

**Comment by dmishe** [comment]
For iOS target version, use `--ios_minimum_os=7`
For arch, use `--ios_cpu=x86_64`

**Comment by perezd** [comment]
I actually want to build a macOS binary, I didn't specify iOS to begin with
it seems to be defaulting to iOS.

**Comment by perezd** [comment]
This started working after a restart..must have been something wrong with Xcode.
