### ISSUE TITLE
Repeated condition on _framework_header_modulemap_partial_impl

### ISSUE THREAD

**Issue by jagobagascon** [bazelbuild/rules_apple#972]
I was having problems compiling my code and I just came across this repeated condition (not related to my problem):
https://github.com/bazelbuild/rules_apple/blob/9640af6837601967c2dcc888831e29041ee9ed9c/apple/internal/partials/static_framework_header_modulemap.bzl#L160

By the comment above it I think it should be something like this (I'm not sure though):
```python
 if any([sdk_dylibs, sdk_frameworks, umbrella_header_name]): 
```

**Comment by thii** [comment]
The suggested change looks right.
