### ISSUE TITLE
generated .ipa path

### ISSUE THREAD

**Issue by fisheye-123** [bazelbuild/rules_apple#997]
I noticed after executing
"bazel build //mypath:myapp"
it print something like:
Target "my app target" is up-to-date:
bazel-out/applebin_ios-ios_x86_64-dbg-ST-50603ff4af65/mypath/myapp.ipa

why the generated ipa is not in bazel-bin directory? is there any way to get a fixed path for the generated ipa?
I am fairly sure some time ago the ipa was generated in ./bazel-bin/mypath/myapp.ipa

**Comment by thii** [comment]
Try to build with `--use_top_level_targets_for_symlinks` flag.

**Comment by fisheye-123** [comment]
awesome, thx!

**Comment by keith** [comment]
Core issue tracked here https://github.com/bazelbuild/bazel/issues/12389
